/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public class ApplicationContext extends FrameListener {
  private transient long swigCPtr;

  protected ApplicationContext(long cPtr, boolean cMemoryOwn) {
    super(OgreBitesJNI.ApplicationContext_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ApplicationContext obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreBitesJNI.delete_ApplicationContext(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    OgreBitesJNI.ApplicationContext_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    OgreBitesJNI.ApplicationContext_change_ownership(this, swigCPtr, true);
  }

  public ApplicationContext(String appName, boolean unused) {
    this(OgreBitesJNI.new_ApplicationContext__SWIG_0(appName, unused), true);
    OgreBitesJNI.ApplicationContext_director_connect(this, swigCPtr, true, true);
  }

  public ApplicationContext(String appName) {
    this(OgreBitesJNI.new_ApplicationContext__SWIG_1(appName), true);
    OgreBitesJNI.ApplicationContext_director_connect(this, swigCPtr, true, true);
  }

  public ApplicationContext() {
    this(OgreBitesJNI.new_ApplicationContext__SWIG_2(), true);
    OgreBitesJNI.ApplicationContext_director_connect(this, swigCPtr, true, true);
  }

  public RenderWindow getRenderWindow() {
    long cPtr = OgreBitesJNI.ApplicationContext_getRenderWindow(swigCPtr, this);
    return (cPtr == 0) ? null : new RenderWindow(cPtr, false);
  }

  public Root getRoot() {
    long cPtr = OgreBitesJNI.ApplicationContext_getRoot(swigCPtr, this);
    return (cPtr == 0) ? null : new Root(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__OverlaySystem getOverlaySystem() {
    long cPtr = OgreBitesJNI.ApplicationContext_getOverlaySystem(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__OverlaySystem(cPtr, false);
  }

  public void _fireInputEventAndroid(SWIGTYPE_p_AInputEvent event, int wheel) {
    OgreBitesJNI.ApplicationContext__fireInputEventAndroid__SWIG_0(swigCPtr, this, SWIGTYPE_p_AInputEvent.getCPtr(event), wheel);
  }

  public void _fireInputEventAndroid(SWIGTYPE_p_AInputEvent event) {
    OgreBitesJNI.ApplicationContext__fireInputEventAndroid__SWIG_1(swigCPtr, this, SWIGTYPE_p_AInputEvent.getCPtr(event));
  }

  public void closeApp() {
    OgreBitesJNI.ApplicationContext_closeApp(swigCPtr, this);
  }

  public boolean frameStarted(FrameEvent evt) {
    return (getClass() == ApplicationContext.class) ? OgreBitesJNI.ApplicationContext_frameStarted(swigCPtr, this, FrameEvent.getCPtr(evt), evt) : OgreBitesJNI.ApplicationContext_frameStartedSwigExplicitApplicationContext(swigCPtr, this, FrameEvent.getCPtr(evt), evt);
  }

  public boolean frameRenderingQueued(FrameEvent evt) {
    return (getClass() == ApplicationContext.class) ? OgreBitesJNI.ApplicationContext_frameRenderingQueued(swigCPtr, this, FrameEvent.getCPtr(evt), evt) : OgreBitesJNI.ApplicationContext_frameRenderingQueuedSwigExplicitApplicationContext(swigCPtr, this, FrameEvent.getCPtr(evt), evt);
  }

  public boolean frameEnded(FrameEvent evt) {
    return (getClass() == ApplicationContext.class) ? OgreBitesJNI.ApplicationContext_frameEnded(swigCPtr, this, FrameEvent.getCPtr(evt), evt) : OgreBitesJNI.ApplicationContext_frameEndedSwigExplicitApplicationContext(swigCPtr, this, FrameEvent.getCPtr(evt), evt);
  }

  public void windowMoved(RenderWindow rw) {
    if (getClass() == ApplicationContext.class) OgreBitesJNI.ApplicationContext_windowMoved(swigCPtr, this, RenderWindow.getCPtr(rw), rw); else OgreBitesJNI.ApplicationContext_windowMovedSwigExplicitApplicationContext(swigCPtr, this, RenderWindow.getCPtr(rw), rw);
  }

  public void windowResized(RenderWindow rw) {
    if (getClass() == ApplicationContext.class) OgreBitesJNI.ApplicationContext_windowResized(swigCPtr, this, RenderWindow.getCPtr(rw), rw); else OgreBitesJNI.ApplicationContext_windowResizedSwigExplicitApplicationContext(swigCPtr, this, RenderWindow.getCPtr(rw), rw);
  }

  public boolean windowClosing(RenderWindow rw) {
    return (getClass() == ApplicationContext.class) ? OgreBitesJNI.ApplicationContext_windowClosing(swigCPtr, this, RenderWindow.getCPtr(rw), rw) : OgreBitesJNI.ApplicationContext_windowClosingSwigExplicitApplicationContext(swigCPtr, this, RenderWindow.getCPtr(rw), rw);
  }

  public void windowClosed(RenderWindow rw) {
    if (getClass() == ApplicationContext.class) OgreBitesJNI.ApplicationContext_windowClosed(swigCPtr, this, RenderWindow.getCPtr(rw), rw); else OgreBitesJNI.ApplicationContext_windowClosedSwigExplicitApplicationContext(swigCPtr, this, RenderWindow.getCPtr(rw), rw);
  }

  public void windowFocusChange(RenderWindow rw) {
    if (getClass() == ApplicationContext.class) OgreBitesJNI.ApplicationContext_windowFocusChange(swigCPtr, this, RenderWindow.getCPtr(rw), rw); else OgreBitesJNI.ApplicationContext_windowFocusChangeSwigExplicitApplicationContext(swigCPtr, this, RenderWindow.getCPtr(rw), rw);
  }

  public void _fireInputEvent(Event event, long windowID) {
    OgreBitesJNI.ApplicationContext__fireInputEvent(swigCPtr, this, Event.getCPtr(event), event, windowID);
  }

  public boolean initialiseRTShaderSystem() {
    return OgreBitesJNI.ApplicationContext_initialiseRTShaderSystem(swigCPtr, this);
  }

  public void setRTSSWriteShadersToDisk(boolean write) {
    OgreBitesJNI.ApplicationContext_setRTSSWriteShadersToDisk(swigCPtr, this, write);
  }

  public void destroyRTShaderSystem() {
    OgreBitesJNI.ApplicationContext_destroyRTShaderSystem(swigCPtr, this);
  }

  public void setup() {
    if (getClass() == ApplicationContext.class) OgreBitesJNI.ApplicationContext_setup(swigCPtr, this); else OgreBitesJNI.ApplicationContext_setupSwigExplicitApplicationContext(swigCPtr, this);
  }

  public void createRoot() {
    if (getClass() == ApplicationContext.class) OgreBitesJNI.ApplicationContext_createRoot(swigCPtr, this); else OgreBitesJNI.ApplicationContext_createRootSwigExplicitApplicationContext(swigCPtr, this);
  }

  public boolean oneTimeConfig() {
    return (getClass() == ApplicationContext.class) ? OgreBitesJNI.ApplicationContext_oneTimeConfig(swigCPtr, this) : OgreBitesJNI.ApplicationContext_oneTimeConfigSwigExplicitApplicationContext(swigCPtr, this);
  }

  public void setWindowGrab(SWIGTYPE_p_ANativeWindow win, boolean grab) {
    OgreBitesJNI.ApplicationContext_setWindowGrab__SWIG_0(swigCPtr, this, SWIGTYPE_p_ANativeWindow.getCPtr(win), grab);
  }

  public void setWindowGrab(SWIGTYPE_p_ANativeWindow win) {
    OgreBitesJNI.ApplicationContext_setWindowGrab__SWIG_1(swigCPtr, this, SWIGTYPE_p_ANativeWindow.getCPtr(win));
  }

  public void setWindowGrab(boolean grab) {
    OgreBitesJNI.ApplicationContext_setWindowGrab__SWIG_2(swigCPtr, this, grab);
  }

  public void setWindowGrab() {
    OgreBitesJNI.ApplicationContext_setWindowGrab__SWIG_3(swigCPtr, this);
  }

  public void locateResources() {
    if (getClass() == ApplicationContext.class) OgreBitesJNI.ApplicationContext_locateResources(swigCPtr, this); else OgreBitesJNI.ApplicationContext_locateResourcesSwigExplicitApplicationContext(swigCPtr, this);
  }

  public void loadResources() {
    if (getClass() == ApplicationContext.class) OgreBitesJNI.ApplicationContext_loadResources(swigCPtr, this); else OgreBitesJNI.ApplicationContext_loadResourcesSwigExplicitApplicationContext(swigCPtr, this);
  }

  public void reconfigure(String renderer, SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t options) {
    if (getClass() == ApplicationContext.class) OgreBitesJNI.ApplicationContext_reconfigure(swigCPtr, this, renderer, SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t.getCPtr(options)); else OgreBitesJNI.ApplicationContext_reconfigureSwigExplicitApplicationContext(swigCPtr, this, renderer, SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t.getCPtr(options));
  }

  public void shutdown() {
    if (getClass() == ApplicationContext.class) OgreBitesJNI.ApplicationContext_shutdown(swigCPtr, this); else OgreBitesJNI.ApplicationContext_shutdownSwigExplicitApplicationContext(swigCPtr, this);
  }

  public void pollEvents() {
    OgreBitesJNI.ApplicationContext_pollEvents(swigCPtr, this);
  }

  public void createDummyScene() {
    OgreBitesJNI.ApplicationContext_createDummyScene(swigCPtr, this);
  }

  public void destroyDummyScene() {
    OgreBitesJNI.ApplicationContext_destroyDummyScene(swigCPtr, this);
  }

  public void enableShaderCache() {
    OgreBitesJNI.ApplicationContext_enableShaderCache(swigCPtr, this);
  }

  public void addInputListener(SWIGTYPE_p_ANativeWindow win, InputListener lis) {
    OgreBitesJNI.ApplicationContext_addInputListener__SWIG_0(swigCPtr, this, SWIGTYPE_p_ANativeWindow.getCPtr(win), InputListener.getCPtr(lis), lis);
  }

  public void addInputListener(InputListener lis) {
    OgreBitesJNI.ApplicationContext_addInputListener__SWIG_1(swigCPtr, this, InputListener.getCPtr(lis), lis);
  }

  public void removeInputListener(SWIGTYPE_p_ANativeWindow win, InputListener lis) {
    OgreBitesJNI.ApplicationContext_removeInputListener__SWIG_0(swigCPtr, this, SWIGTYPE_p_ANativeWindow.getCPtr(win), InputListener.getCPtr(lis), lis);
  }

  public void removeInputListener(InputListener lis) {
    OgreBitesJNI.ApplicationContext_removeInputListener__SWIG_1(swigCPtr, this, InputListener.getCPtr(lis), lis);
  }

  public NativeWindowPair createWindow(String name, long w, long h, SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t miscParams) {
    return new NativeWindowPair((getClass() == ApplicationContext.class) ? OgreBitesJNI.ApplicationContext_createWindow__SWIG_0(swigCPtr, this, name, w, h, SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t.getCPtr(miscParams)) : OgreBitesJNI.ApplicationContext_createWindowSwigExplicitApplicationContext__SWIG_0(swigCPtr, this, name, w, h, SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t.getCPtr(miscParams)), true);
  }

  public NativeWindowPair createWindow(String name, long w, long h) {
    return new NativeWindowPair((getClass() == ApplicationContext.class) ? OgreBitesJNI.ApplicationContext_createWindow__SWIG_1(swigCPtr, this, name, w, h) : OgreBitesJNI.ApplicationContext_createWindowSwigExplicitApplicationContext__SWIG_1(swigCPtr, this, name, w, h), true);
  }

  public NativeWindowPair createWindow(String name, long w) {
    return new NativeWindowPair((getClass() == ApplicationContext.class) ? OgreBitesJNI.ApplicationContext_createWindow__SWIG_2(swigCPtr, this, name, w) : OgreBitesJNI.ApplicationContext_createWindowSwigExplicitApplicationContext__SWIG_2(swigCPtr, this, name, w), true);
  }

  public NativeWindowPair createWindow(String name) {
    return new NativeWindowPair((getClass() == ApplicationContext.class) ? OgreBitesJNI.ApplicationContext_createWindow__SWIG_3(swigCPtr, this, name) : OgreBitesJNI.ApplicationContext_createWindowSwigExplicitApplicationContext__SWIG_3(swigCPtr, this, name), true);
  }

  public static String getDefaultMediaDir() {
    return OgreBitesJNI.ApplicationContext_getDefaultMediaDir();
  }

  public void initAppForAndroid(Object assetManager, Object surface) {
    OgreBitesJNI.ApplicationContext_initAppForAndroid(swigCPtr, this, assetManager, surface);
  }

}
