/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public class AtomAbstractNode extends AbstractNode {
  private transient long swigCPtr;

  protected AtomAbstractNode(long cPtr, boolean cMemoryOwn) {
    super(OgreJNI.AtomAbstractNode_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AtomAbstractNode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_AtomAbstractNode(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setValue(String value) {
    OgreJNI.AtomAbstractNode_value_set(swigCPtr, this, value);
  }

  public String getValue() {
    return OgreJNI.AtomAbstractNode_value_get(swigCPtr, this);
  }

  public void setId(long value) {
    OgreJNI.AtomAbstractNode_id_set(swigCPtr, this, value);
  }

  public long getId() {
    return OgreJNI.AtomAbstractNode_id_get(swigCPtr, this);
  }

  public AtomAbstractNode(AbstractNode ptr) {
    this(OgreJNI.new_AtomAbstractNode(AbstractNode.getCPtr(ptr), ptr), true);
  }

  public AbstractNode clone() {
    long cPtr = OgreJNI.AtomAbstractNode_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new AbstractNode(cPtr, false);
  }

}
