/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public final class ButtonState {
  public final static ButtonState BS_UP = new ButtonState("BS_UP");
  public final static ButtonState BS_OVER = new ButtonState("BS_OVER");
  public final static ButtonState BS_DOWN = new ButtonState("BS_DOWN");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ButtonState swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ButtonState.class + " with value " + swigValue);
  }

  private ButtonState(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ButtonState(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ButtonState(String swigName, ButtonState swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ButtonState[] swigValues = { BS_UP, BS_OVER, BS_DOWN };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

