/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public final class ClipResult {
  public final static ClipResult CLIPPED_NONE = new ClipResult("CLIPPED_NONE", OgreJNI.CLIPPED_NONE_get());
  public final static ClipResult CLIPPED_SOME = new ClipResult("CLIPPED_SOME", OgreJNI.CLIPPED_SOME_get());
  public final static ClipResult CLIPPED_ALL = new ClipResult("CLIPPED_ALL", OgreJNI.CLIPPED_ALL_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ClipResult swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ClipResult.class + " with value " + swigValue);
  }

  private ClipResult(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ClipResult(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ClipResult(String swigName, ClipResult swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ClipResult[] swigValues = { CLIPPED_NONE, CLIPPED_SOME, CLIPPED_ALL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

