/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public class ConcreteNode {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ConcreteNode(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConcreteNode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_ConcreteNode(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setToken(String value) {
    OgreJNI.ConcreteNode_token_set(swigCPtr, this, value);
  }

  public String getToken() {
    return OgreJNI.ConcreteNode_token_get(swigCPtr, this);
  }

  public void setFile(String value) {
    OgreJNI.ConcreteNode_file_set(swigCPtr, this, value);
  }

  public String getFile() {
    return OgreJNI.ConcreteNode_file_get(swigCPtr, this);
  }

  public void setLine(long value) {
    OgreJNI.ConcreteNode_line_set(swigCPtr, this, value);
  }

  public long getLine() {
    return OgreJNI.ConcreteNode_line_get(swigCPtr, this);
  }

  public void setType(ConcreteNodeType value) {
    OgreJNI.ConcreteNode_type_set(swigCPtr, this, value.swigValue());
  }

  public ConcreteNodeType getType() {
    return ConcreteNodeType.swigToEnum(OgreJNI.ConcreteNode_type_get(swigCPtr, this));
  }

  public void setChildren(SWIGTYPE_p_Ogre__listT_Ogre__SharedPtrT_Ogre__ConcreteNode_t_t__type value) {
    OgreJNI.ConcreteNode_children_set(swigCPtr, this, SWIGTYPE_p_Ogre__listT_Ogre__SharedPtrT_Ogre__ConcreteNode_t_t__type.getCPtr(value));
  }

  public SWIGTYPE_p_Ogre__listT_Ogre__SharedPtrT_Ogre__ConcreteNode_t_t__type getChildren() {
    long cPtr = OgreJNI.ConcreteNode_children_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__listT_Ogre__SharedPtrT_Ogre__ConcreteNode_t_t__type(cPtr, false);
  }

  public void setParent(ConcreteNode value) {
    OgreJNI.ConcreteNode_parent_set(swigCPtr, this, ConcreteNode.getCPtr(value), value);
  }

  public ConcreteNode getParent() {
    long cPtr = OgreJNI.ConcreteNode_parent_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ConcreteNode(cPtr, false);
  }

  public ConcreteNode() {
    this(OgreJNI.new_ConcreteNode(), true);
  }

}
