/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public class FileInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FileInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FileInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_FileInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setArchive(Archive value) {
    OgreJNI.FileInfo_archive_set(swigCPtr, this, Archive.getCPtr(value), value);
  }

  public Archive getArchive() {
    long cPtr = OgreJNI.FileInfo_archive_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Archive(cPtr, false);
  }

  public void setFilename(String value) {
    OgreJNI.FileInfo_filename_set(swigCPtr, this, value);
  }

  public String getFilename() {
    return OgreJNI.FileInfo_filename_get(swigCPtr, this);
  }

  public void setPath(String value) {
    OgreJNI.FileInfo_path_set(swigCPtr, this, value);
  }

  public String getPath() {
    return OgreJNI.FileInfo_path_get(swigCPtr, this);
  }

  public void setBasename(String value) {
    OgreJNI.FileInfo_basename_set(swigCPtr, this, value);
  }

  public String getBasename() {
    return OgreJNI.FileInfo_basename_get(swigCPtr, this);
  }

  public void setCompressedSize(long value) {
    OgreJNI.FileInfo_compressedSize_set(swigCPtr, this, value);
  }

  public long getCompressedSize() {
    return OgreJNI.FileInfo_compressedSize_get(swigCPtr, this);
  }

  public void setUncompressedSize(long value) {
    OgreJNI.FileInfo_uncompressedSize_set(swigCPtr, this, value);
  }

  public long getUncompressedSize() {
    return OgreJNI.FileInfo_uncompressedSize_get(swigCPtr, this);
  }

  public FileInfo() {
    this(OgreJNI.new_FileInfo(), true);
  }

}
