/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public final class FilterType {
  public final static FilterType FT_MIN = new FilterType("FT_MIN");
  public final static FilterType FT_MAG = new FilterType("FT_MAG");
  public final static FilterType FT_MIP = new FilterType("FT_MIP");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FilterType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FilterType.class + " with value " + swigValue);
  }

  private FilterType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FilterType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FilterType(String swigName, FilterType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FilterType[] swigValues = { FT_MIN, FT_MAG, FT_MIP };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

