/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public final class GpuParamVariability {
  public final static GpuParamVariability GPV_GLOBAL = new GpuParamVariability("GPV_GLOBAL", OgreJNI.GPV_GLOBAL_get());
  public final static GpuParamVariability GPV_PER_OBJECT = new GpuParamVariability("GPV_PER_OBJECT", OgreJNI.GPV_PER_OBJECT_get());
  public final static GpuParamVariability GPV_LIGHTS = new GpuParamVariability("GPV_LIGHTS", OgreJNI.GPV_LIGHTS_get());
  public final static GpuParamVariability GPV_PASS_ITERATION_NUMBER = new GpuParamVariability("GPV_PASS_ITERATION_NUMBER", OgreJNI.GPV_PASS_ITERATION_NUMBER_get());
  public final static GpuParamVariability GPV_ALL = new GpuParamVariability("GPV_ALL", OgreJNI.GPV_ALL_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GpuParamVariability swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GpuParamVariability.class + " with value " + swigValue);
  }

  private GpuParamVariability(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GpuParamVariability(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GpuParamVariability(String swigName, GpuParamVariability swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GpuParamVariability[] swigValues = { GPV_GLOBAL, GPV_PER_OBJECT, GPV_LIGHTS, GPV_PASS_ITERATION_NUMBER, GPV_ALL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

