/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public class GpuProgramPtr {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GpuProgramPtr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GpuProgramPtr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_GpuProgramPtr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GpuProgramPtr() {
    this(OgreJNI.new_GpuProgramPtr__SWIG_1(), true);
  }

  public GpuProgramPtr(GpuProgramPtr r) {
    this(OgreJNI.new_GpuProgramPtr__SWIG_2(GpuProgramPtr.getCPtr(r), r), true);
  }

  public GpuProgram __ref__() {
    return new GpuProgram(OgreJNI.GpuProgramPtr___ref__(swigCPtr, this), false);
  }

  public GpuProgram __deref__() {
    long cPtr = OgreJNI.GpuProgramPtr___deref__(swigCPtr, this);
    return (cPtr == 0) ? null : new GpuProgram(cPtr, false);
  }

  public GpuProgram get() {
    long cPtr = OgreJNI.GpuProgramPtr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new GpuProgram(cPtr, false);
  }

  public boolean unique() {
    return OgreJNI.GpuProgramPtr_unique(swigCPtr, this);
  }

  public int use_count() {
    return OgreJNI.GpuProgramPtr_use_count(swigCPtr, this);
  }

  public void reset() {
    OgreJNI.GpuProgramPtr_reset__SWIG_0(swigCPtr, this);
  }

  public void reset(GpuProgram rep) {
    OgreJNI.GpuProgramPtr_reset__SWIG_1(swigCPtr, this, GpuProgram.getCPtr(rep), rep);
  }

  public String getProgramTypeName(GpuProgramType programType) {
    return OgreJNI.GpuProgramPtr_getProgramTypeName(swigCPtr, this, programType.swigValue());
  }

  public void setSourceFile(String filename) {
    OgreJNI.GpuProgramPtr_setSourceFile(swigCPtr, this, filename);
  }

  public void setSource(String source) {
    OgreJNI.GpuProgramPtr_setSource(swigCPtr, this, source);
  }

  public String getSyntaxCode() {
    return OgreJNI.GpuProgramPtr_getSyntaxCode(swigCPtr, this);
  }

  public void setSyntaxCode(String syntax) {
    OgreJNI.GpuProgramPtr_setSyntaxCode(swigCPtr, this, syntax);
  }

  public String getSourceFile() {
    return OgreJNI.GpuProgramPtr_getSourceFile(swigCPtr, this);
  }

  public String getSource() {
    return OgreJNI.GpuProgramPtr_getSource(swigCPtr, this);
  }

  public void setType(GpuProgramType t) {
    OgreJNI.GpuProgramPtr_setType(swigCPtr, this, t.swigValue());
  }

  public GpuProgram _getBindingDelegate() {
    long cPtr = OgreJNI.GpuProgramPtr__getBindingDelegate(swigCPtr, this);
    return (cPtr == 0) ? null : new GpuProgram(cPtr, false);
  }

  public boolean isSupported() {
    return OgreJNI.GpuProgramPtr_isSupported(swigCPtr, this);
  }

  public SWIGTYPE_p_Ogre__SharedPtrT_Ogre__GpuProgramParameters_t createParameters() {
    return new SWIGTYPE_p_Ogre__SharedPtrT_Ogre__GpuProgramParameters_t(OgreJNI.GpuProgramPtr_createParameters(swigCPtr, this), true);
  }

  public void setSkeletalAnimationIncluded(boolean included) {
    OgreJNI.GpuProgramPtr_setSkeletalAnimationIncluded(swigCPtr, this, included);
  }

  public boolean isSkeletalAnimationIncluded() {
    return OgreJNI.GpuProgramPtr_isSkeletalAnimationIncluded(swigCPtr, this);
  }

  public void setMorphAnimationIncluded(boolean included) {
    OgreJNI.GpuProgramPtr_setMorphAnimationIncluded(swigCPtr, this, included);
  }

  public void setPoseAnimationIncluded(int poseCount) {
    OgreJNI.GpuProgramPtr_setPoseAnimationIncluded(swigCPtr, this, poseCount);
  }

  public boolean isMorphAnimationIncluded() {
    return OgreJNI.GpuProgramPtr_isMorphAnimationIncluded(swigCPtr, this);
  }

  public boolean isPoseAnimationIncluded() {
    return OgreJNI.GpuProgramPtr_isPoseAnimationIncluded(swigCPtr, this);
  }

  public int getNumberOfPosesIncluded() {
    return OgreJNI.GpuProgramPtr_getNumberOfPosesIncluded(swigCPtr, this);
  }

  public void setVertexTextureFetchRequired(boolean r) {
    OgreJNI.GpuProgramPtr_setVertexTextureFetchRequired(swigCPtr, this, r);
  }

  public boolean isVertexTextureFetchRequired() {
    return OgreJNI.GpuProgramPtr_isVertexTextureFetchRequired(swigCPtr, this);
  }

  public void setAdjacencyInfoRequired(boolean r) {
    OgreJNI.GpuProgramPtr_setAdjacencyInfoRequired(swigCPtr, this, r);
  }

  public boolean isAdjacencyInfoRequired() {
    return OgreJNI.GpuProgramPtr_isAdjacencyInfoRequired(swigCPtr, this);
  }

  public void setComputeGroupDimensions(Vector3 dimensions) {
    OgreJNI.GpuProgramPtr_setComputeGroupDimensions(swigCPtr, this, Vector3.getCPtr(dimensions), dimensions);
  }

  public Vector3 getComputeGroupDimensions() {
    return new Vector3(OgreJNI.GpuProgramPtr_getComputeGroupDimensions(swigCPtr, this), true);
  }

  public SWIGTYPE_p_Ogre__SharedPtrT_Ogre__GpuProgramParameters_t getDefaultParameters() {
    return new SWIGTYPE_p_Ogre__SharedPtrT_Ogre__GpuProgramParameters_t(OgreJNI.GpuProgramPtr_getDefaultParameters(swigCPtr, this), true);
  }

  public boolean hasDefaultParameters() {
    return OgreJNI.GpuProgramPtr_hasDefaultParameters(swigCPtr, this);
  }

  public boolean getPassSurfaceAndLightStates() {
    return OgreJNI.GpuProgramPtr_getPassSurfaceAndLightStates(swigCPtr, this);
  }

  public boolean getPassFogStates() {
    return OgreJNI.GpuProgramPtr_getPassFogStates(swigCPtr, this);
  }

  public boolean getPassTransformStates() {
    return OgreJNI.GpuProgramPtr_getPassTransformStates(swigCPtr, this);
  }

  public String getLanguage() {
    return OgreJNI.GpuProgramPtr_getLanguage(swigCPtr, this);
  }

  public boolean hasCompileError() {
    return OgreJNI.GpuProgramPtr_hasCompileError(swigCPtr, this);
  }

  public void resetCompileError() {
    OgreJNI.GpuProgramPtr_resetCompileError(swigCPtr, this);
  }

  public void setManualNamedConstants(GpuNamedConstants namedConstants) {
    OgreJNI.GpuProgramPtr_setManualNamedConstants(swigCPtr, this, GpuNamedConstants.getCPtr(namedConstants), namedConstants);
  }

  public void setManualNamedConstantsFile(String paramDefFile) {
    OgreJNI.GpuProgramPtr_setManualNamedConstantsFile(swigCPtr, this, paramDefFile);
  }

  public String getManualNamedConstantsFile() {
    return OgreJNI.GpuProgramPtr_getManualNamedConstantsFile(swigCPtr, this);
  }

  public GpuNamedConstants getConstantDefinitions() {
    return new GpuNamedConstants(OgreJNI.GpuProgramPtr_getConstantDefinitions(swigCPtr, this), false);
  }

  public long calculateSize() {
    return OgreJNI.GpuProgramPtr_calculateSize(swigCPtr, this);
  }

  public void prepare(boolean backgroundThread) {
    OgreJNI.GpuProgramPtr_prepare__SWIG_0(swigCPtr, this, backgroundThread);
  }

  public void prepare() {
    OgreJNI.GpuProgramPtr_prepare__SWIG_1(swigCPtr, this);
  }

  public void load(boolean backgroundThread) {
    OgreJNI.GpuProgramPtr_load__SWIG_0(swigCPtr, this, backgroundThread);
  }

  public void load() {
    OgreJNI.GpuProgramPtr_load__SWIG_1(swigCPtr, this);
  }

  public void reload(Resource.LoadingFlags flags) {
    OgreJNI.GpuProgramPtr_reload__SWIG_0(swigCPtr, this, flags.swigValue());
  }

  public void reload() {
    OgreJNI.GpuProgramPtr_reload__SWIG_1(swigCPtr, this);
  }

  public boolean isReloadable() {
    return OgreJNI.GpuProgramPtr_isReloadable(swigCPtr, this);
  }

  public boolean isManuallyLoaded() {
    return OgreJNI.GpuProgramPtr_isManuallyLoaded(swigCPtr, this);
  }

  public void unload() {
    OgreJNI.GpuProgramPtr_unload(swigCPtr, this);
  }

  public long getSize() {
    return OgreJNI.GpuProgramPtr_getSize(swigCPtr, this);
  }

  public void touch() {
    OgreJNI.GpuProgramPtr_touch(swigCPtr, this);
  }

  public String getName() {
    return OgreJNI.GpuProgramPtr_getName(swigCPtr, this);
  }

  public java.math.BigInteger getHandle() {
    return OgreJNI.GpuProgramPtr_getHandle(swigCPtr, this);
  }

  public boolean isPrepared() {
    return OgreJNI.GpuProgramPtr_isPrepared(swigCPtr, this);
  }

  public boolean isLoaded() {
    return OgreJNI.GpuProgramPtr_isLoaded(swigCPtr, this);
  }

  public boolean isLoading() {
    return OgreJNI.GpuProgramPtr_isLoading(swigCPtr, this);
  }

  public Resource.LoadingState getLoadingState() {
    return Resource.LoadingState.swigToEnum(OgreJNI.GpuProgramPtr_getLoadingState(swigCPtr, this));
  }

  public boolean isBackgroundLoaded() {
    return OgreJNI.GpuProgramPtr_isBackgroundLoaded(swigCPtr, this);
  }

  public void setBackgroundLoaded(boolean bl) {
    OgreJNI.GpuProgramPtr_setBackgroundLoaded(swigCPtr, this, bl);
  }

  public void escalateLoading() {
    OgreJNI.GpuProgramPtr_escalateLoading(swigCPtr, this);
  }

  public void addListener(Resource.Listener lis) {
    OgreJNI.GpuProgramPtr_addListener(swigCPtr, this, Resource.Listener.getCPtr(lis), lis);
  }

  public void removeListener(Resource.Listener lis) {
    OgreJNI.GpuProgramPtr_removeListener(swigCPtr, this, Resource.Listener.getCPtr(lis), lis);
  }

  public String getGroup() {
    return OgreJNI.GpuProgramPtr_getGroup(swigCPtr, this);
  }

  public void changeGroupOwnership(String newGroup) {
    OgreJNI.GpuProgramPtr_changeGroupOwnership(swigCPtr, this, newGroup);
  }

  public ResourceManager getCreator() {
    long cPtr = OgreJNI.GpuProgramPtr_getCreator(swigCPtr, this);
    return (cPtr == 0) ? null : new ResourceManager(cPtr, false);
  }

  public String getOrigin() {
    return OgreJNI.GpuProgramPtr_getOrigin(swigCPtr, this);
  }

  public void _notifyOrigin(String origin) {
    OgreJNI.GpuProgramPtr__notifyOrigin(swigCPtr, this, origin);
  }

  public long getStateCount() {
    return OgreJNI.GpuProgramPtr_getStateCount(swigCPtr, this);
  }

  public void _dirtyState() {
    OgreJNI.GpuProgramPtr__dirtyState(swigCPtr, this);
  }

  public void _fireLoadingComplete(boolean wasBackgroundLoaded) {
    OgreJNI.GpuProgramPtr__fireLoadingComplete(swigCPtr, this, wasBackgroundLoaded);
  }

  public void _firePreparingComplete(boolean wasBackgroundLoaded) {
    OgreJNI.GpuProgramPtr__firePreparingComplete(swigCPtr, this, wasBackgroundLoaded);
  }

  public void _fireUnloadingComplete() {
    OgreJNI.GpuProgramPtr__fireUnloadingComplete(swigCPtr, this);
  }

  public ParamDictionary getParamDictionary() {
    long cPtr = OgreJNI.GpuProgramPtr_getParamDictionary__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new ParamDictionary(cPtr, false);
  }

  public SWIGTYPE_p_Ogre__vectorT_Ogre__ParameterDef_t__type getParameters() {
    return new SWIGTYPE_p_Ogre__vectorT_Ogre__ParameterDef_t__type(OgreJNI.GpuProgramPtr_getParameters(swigCPtr, this), false);
  }

  public boolean setParameter(String name, String value) {
    return OgreJNI.GpuProgramPtr_setParameter(swigCPtr, this, name, value);
  }

  public void setParameterList(SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t paramList) {
    OgreJNI.GpuProgramPtr_setParameterList(swigCPtr, this, SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t.getCPtr(paramList));
  }

  public String getParameter(String name) {
    return OgreJNI.GpuProgramPtr_getParameter(swigCPtr, this, name);
  }

  public void copyParametersTo(StringInterface dest) {
    OgreJNI.GpuProgramPtr_copyParametersTo(swigCPtr, this, StringInterface.getCPtr(dest), dest);
  }

  public void cleanupDictionary() {
    OgreJNI.GpuProgramPtr_cleanupDictionary(swigCPtr, this);
  }

}
