/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public final class GPUVendor {
  public final static GPUVendor GPU_UNKNOWN = new GPUVendor("GPU_UNKNOWN", OgreJNI.GPU_UNKNOWN_get());
  public final static GPUVendor GPU_NVIDIA = new GPUVendor("GPU_NVIDIA", OgreJNI.GPU_NVIDIA_get());
  public final static GPUVendor GPU_AMD = new GPUVendor("GPU_AMD", OgreJNI.GPU_AMD_get());
  public final static GPUVendor GPU_INTEL = new GPUVendor("GPU_INTEL", OgreJNI.GPU_INTEL_get());
  public final static GPUVendor GPU_S3 = new GPUVendor("GPU_S3", OgreJNI.GPU_S3_get());
  public final static GPUVendor GPU_MATROX = new GPUVendor("GPU_MATROX", OgreJNI.GPU_MATROX_get());
  public final static GPUVendor GPU_3DLABS = new GPUVendor("GPU_3DLABS", OgreJNI.GPU_3DLABS_get());
  public final static GPUVendor GPU_SIS = new GPUVendor("GPU_SIS", OgreJNI.GPU_SIS_get());
  public final static GPUVendor GPU_IMAGINATION_TECHNOLOGIES = new GPUVendor("GPU_IMAGINATION_TECHNOLOGIES", OgreJNI.GPU_IMAGINATION_TECHNOLOGIES_get());
  public final static GPUVendor GPU_APPLE = new GPUVendor("GPU_APPLE", OgreJNI.GPU_APPLE_get());
  public final static GPUVendor GPU_NOKIA = new GPUVendor("GPU_NOKIA", OgreJNI.GPU_NOKIA_get());
  public final static GPUVendor GPU_MS_SOFTWARE = new GPUVendor("GPU_MS_SOFTWARE", OgreJNI.GPU_MS_SOFTWARE_get());
  public final static GPUVendor GPU_MS_WARP = new GPUVendor("GPU_MS_WARP", OgreJNI.GPU_MS_WARP_get());
  public final static GPUVendor GPU_ARM = new GPUVendor("GPU_ARM", OgreJNI.GPU_ARM_get());
  public final static GPUVendor GPU_QUALCOMM = new GPUVendor("GPU_QUALCOMM", OgreJNI.GPU_QUALCOMM_get());
  public final static GPUVendor GPU_MOZILLA = new GPUVendor("GPU_MOZILLA", OgreJNI.GPU_MOZILLA_get());
  public final static GPUVendor GPU_WEBKIT = new GPUVendor("GPU_WEBKIT", OgreJNI.GPU_WEBKIT_get());
  public final static GPUVendor GPU_VENDOR_COUNT = new GPUVendor("GPU_VENDOR_COUNT", OgreJNI.GPU_VENDOR_COUNT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GPUVendor swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GPUVendor.class + " with value " + swigValue);
  }

  private GPUVendor(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GPUVendor(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GPUVendor(String swigName, GPUVendor swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GPUVendor[] swigValues = { GPU_UNKNOWN, GPU_NVIDIA, GPU_AMD, GPU_INTEL, GPU_S3, GPU_MATROX, GPU_3DLABS, GPU_SIS, GPU_IMAGINATION_TECHNOLOGIES, GPU_APPLE, GPU_NOKIA, GPU_MS_SOFTWARE, GPU_MS_WARP, GPU_ARM, GPU_QUALCOMM, GPU_MOZILLA, GPU_WEBKIT, GPU_VENDOR_COUNT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

