/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public class HardwarePixelBufferPtr {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected HardwarePixelBufferPtr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HardwarePixelBufferPtr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_HardwarePixelBufferPtr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public HardwarePixelBufferPtr() {
    this(OgreJNI.new_HardwarePixelBufferPtr__SWIG_1(), true);
  }

  public HardwarePixelBufferPtr(HardwarePixelBufferPtr r) {
    this(OgreJNI.new_HardwarePixelBufferPtr__SWIG_2(HardwarePixelBufferPtr.getCPtr(r), r), true);
  }

  public HardwarePixelBuffer __ref__() {
    return new HardwarePixelBuffer(OgreJNI.HardwarePixelBufferPtr___ref__(swigCPtr, this), false);
  }

  public HardwarePixelBuffer __deref__() {
    long cPtr = OgreJNI.HardwarePixelBufferPtr___deref__(swigCPtr, this);
    return (cPtr == 0) ? null : new HardwarePixelBuffer(cPtr, false);
  }

  public HardwarePixelBuffer get() {
    long cPtr = OgreJNI.HardwarePixelBufferPtr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new HardwarePixelBuffer(cPtr, false);
  }

  public boolean unique() {
    return OgreJNI.HardwarePixelBufferPtr_unique(swigCPtr, this);
  }

  public int use_count() {
    return OgreJNI.HardwarePixelBufferPtr_use_count(swigCPtr, this);
  }

  public void reset() {
    OgreJNI.HardwarePixelBufferPtr_reset__SWIG_0(swigCPtr, this);
  }

  public void reset(HardwarePixelBuffer rep) {
    OgreJNI.HardwarePixelBufferPtr_reset__SWIG_1(swigCPtr, this, HardwarePixelBuffer.getCPtr(rep), rep);
  }

  public PixelBox getCurrentLock() {
    return new PixelBox(OgreJNI.HardwarePixelBufferPtr_getCurrentLock(swigCPtr, this), false);
  }

  public void readData(long offset, long length, SWIGTYPE_p_void pDest) {
    OgreJNI.HardwarePixelBufferPtr_readData(swigCPtr, this, offset, length, SWIGTYPE_p_void.getCPtr(pDest));
  }

  public void writeData(long offset, long length, SWIGTYPE_p_void pSource, boolean discardWholeBuffer) {
    OgreJNI.HardwarePixelBufferPtr_writeData__SWIG_0(swigCPtr, this, offset, length, SWIGTYPE_p_void.getCPtr(pSource), discardWholeBuffer);
  }

  public void writeData(long offset, long length, SWIGTYPE_p_void pSource) {
    OgreJNI.HardwarePixelBufferPtr_writeData__SWIG_1(swigCPtr, this, offset, length, SWIGTYPE_p_void.getCPtr(pSource));
  }

  public void blit(HardwarePixelBufferPtr src, Box srcBox, Box dstBox) {
    OgreJNI.HardwarePixelBufferPtr_blit__SWIG_0(swigCPtr, this, HardwarePixelBufferPtr.getCPtr(src), src, Box.getCPtr(srcBox), srcBox, Box.getCPtr(dstBox), dstBox);
  }

  public void blit(HardwarePixelBufferPtr src) {
    OgreJNI.HardwarePixelBufferPtr_blit__SWIG_1(swigCPtr, this, HardwarePixelBufferPtr.getCPtr(src), src);
  }

  public void blitFromMemory(PixelBox src, Box dstBox) {
    OgreJNI.HardwarePixelBufferPtr_blitFromMemory__SWIG_0(swigCPtr, this, PixelBox.getCPtr(src), src, Box.getCPtr(dstBox), dstBox);
  }

  public void blitFromMemory(PixelBox src) {
    OgreJNI.HardwarePixelBufferPtr_blitFromMemory__SWIG_1(swigCPtr, this, PixelBox.getCPtr(src), src);
  }

  public void blitToMemory(Box srcBox, PixelBox dst) {
    OgreJNI.HardwarePixelBufferPtr_blitToMemory__SWIG_0(swigCPtr, this, Box.getCPtr(srcBox), srcBox, PixelBox.getCPtr(dst), dst);
  }

  public void blitToMemory(PixelBox dst) {
    OgreJNI.HardwarePixelBufferPtr_blitToMemory__SWIG_1(swigCPtr, this, PixelBox.getCPtr(dst), dst);
  }

  public RenderTexture getRenderTarget(long slice) {
    long cPtr = OgreJNI.HardwarePixelBufferPtr_getRenderTarget__SWIG_0(swigCPtr, this, slice);
    return (cPtr == 0) ? null : new RenderTexture(cPtr, false);
  }

  public RenderTexture getRenderTarget() {
    long cPtr = OgreJNI.HardwarePixelBufferPtr_getRenderTarget__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new RenderTexture(cPtr, false);
  }

  public long getWidth() {
    return OgreJNI.HardwarePixelBufferPtr_getWidth(swigCPtr, this);
  }

  public long getHeight() {
    return OgreJNI.HardwarePixelBufferPtr_getHeight(swigCPtr, this);
  }

  public long getDepth() {
    return OgreJNI.HardwarePixelBufferPtr_getDepth(swigCPtr, this);
  }

  public PixelFormat getFormat() {
    return PixelFormat.swigToEnum(OgreJNI.HardwarePixelBufferPtr_getFormat(swigCPtr, this));
  }

  public SWIGTYPE_p_void lock(long offset, long length, HardwareBuffer.LockOptions options, HardwareBuffer.UploadOptions uploadOpt) {
    long cPtr = OgreJNI.HardwarePixelBufferPtr_lock__SWIG_0(swigCPtr, this, offset, length, options.swigValue(), uploadOpt.swigValue());
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SWIGTYPE_p_void lock(long offset, long length, HardwareBuffer.LockOptions options) {
    long cPtr = OgreJNI.HardwarePixelBufferPtr_lock__SWIG_1(swigCPtr, this, offset, length, options.swigValue());
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SWIGTYPE_p_void lock(HardwareBuffer.LockOptions options, HardwareBuffer.UploadOptions uploadOpt) {
    long cPtr = OgreJNI.HardwarePixelBufferPtr_lock__SWIG_2(swigCPtr, this, options.swigValue(), uploadOpt.swigValue());
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SWIGTYPE_p_void lock(HardwareBuffer.LockOptions options) {
    long cPtr = OgreJNI.HardwarePixelBufferPtr_lock__SWIG_3(swigCPtr, this, options.swigValue());
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void unlock() {
    OgreJNI.HardwarePixelBufferPtr_unlock(swigCPtr, this);
  }

  public void copyData(HardwareBuffer srcBuffer, long srcOffset, long dstOffset, long length, boolean discardWholeBuffer) {
    OgreJNI.HardwarePixelBufferPtr_copyData__SWIG_0(swigCPtr, this, HardwareBuffer.getCPtr(srcBuffer), srcBuffer, srcOffset, dstOffset, length, discardWholeBuffer);
  }

  public void copyData(HardwareBuffer srcBuffer, long srcOffset, long dstOffset, long length) {
    OgreJNI.HardwarePixelBufferPtr_copyData__SWIG_1(swigCPtr, this, HardwareBuffer.getCPtr(srcBuffer), srcBuffer, srcOffset, dstOffset, length);
  }

  public void copyData(HardwareBuffer srcBuffer) {
    OgreJNI.HardwarePixelBufferPtr_copyData__SWIG_2(swigCPtr, this, HardwareBuffer.getCPtr(srcBuffer), srcBuffer);
  }

  public void _updateFromShadow() {
    OgreJNI.HardwarePixelBufferPtr__updateFromShadow(swigCPtr, this);
  }

  public long getSizeInBytes() {
    return OgreJNI.HardwarePixelBufferPtr_getSizeInBytes(swigCPtr, this);
  }

  public HardwareBuffer.Usage getUsage() {
    return HardwareBuffer.Usage.swigToEnum(OgreJNI.HardwarePixelBufferPtr_getUsage(swigCPtr, this));
  }

  public boolean isSystemMemory() {
    return OgreJNI.HardwarePixelBufferPtr_isSystemMemory(swigCPtr, this);
  }

  public boolean hasShadowBuffer() {
    return OgreJNI.HardwarePixelBufferPtr_hasShadowBuffer(swigCPtr, this);
  }

  public boolean isLocked() {
    return OgreJNI.HardwarePixelBufferPtr_isLocked(swigCPtr, this);
  }

  public void suppressHardwareUpdate(boolean suppress) {
    OgreJNI.HardwarePixelBufferPtr_suppressHardwareUpdate(swigCPtr, this, suppress);
  }

}
