/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public class HardwareCounterBufferPtr {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected HardwareCounterBufferPtr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HardwareCounterBufferPtr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_HardwareCounterBufferPtr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public HardwareCounterBufferPtr() {
    this(OgreJNI.new_HardwareCounterBufferPtr__SWIG_1(), true);
  }

  public HardwareCounterBufferPtr(HardwareCounterBufferPtr r) {
    this(OgreJNI.new_HardwareCounterBufferPtr__SWIG_2(HardwareCounterBufferPtr.getCPtr(r), r), true);
  }

  public HardwareCounterBuffer __ref__() {
    return new HardwareCounterBuffer(OgreJNI.HardwareCounterBufferPtr___ref__(swigCPtr, this), false);
  }

  public HardwareCounterBuffer __deref__() {
    long cPtr = OgreJNI.HardwareCounterBufferPtr___deref__(swigCPtr, this);
    return (cPtr == 0) ? null : new HardwareCounterBuffer(cPtr, false);
  }

  public HardwareCounterBuffer get() {
    long cPtr = OgreJNI.HardwareCounterBufferPtr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new HardwareCounterBuffer(cPtr, false);
  }

  public boolean unique() {
    return OgreJNI.HardwareCounterBufferPtr_unique(swigCPtr, this);
  }

  public int use_count() {
    return OgreJNI.HardwareCounterBufferPtr_use_count(swigCPtr, this);
  }

  public void reset() {
    OgreJNI.HardwareCounterBufferPtr_reset__SWIG_0(swigCPtr, this);
  }

  public void reset(HardwareCounterBuffer rep) {
    OgreJNI.HardwareCounterBufferPtr_reset__SWIG_1(swigCPtr, this, HardwareCounterBuffer.getCPtr(rep), rep);
  }

  public HardwareBufferManagerBase getManager() {
    long cPtr = OgreJNI.HardwareCounterBufferPtr_getManager(swigCPtr, this);
    return (cPtr == 0) ? null : new HardwareBufferManagerBase(cPtr, false);
  }

  public String getName() {
    return OgreJNI.HardwareCounterBufferPtr_getName(swigCPtr, this);
  }

  public SWIGTYPE_p_void lock(long offset, long length, HardwareBuffer.LockOptions options, HardwareBuffer.UploadOptions uploadOpt) {
    long cPtr = OgreJNI.HardwareCounterBufferPtr_lock__SWIG_0(swigCPtr, this, offset, length, options.swigValue(), uploadOpt.swigValue());
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SWIGTYPE_p_void lock(long offset, long length, HardwareBuffer.LockOptions options) {
    long cPtr = OgreJNI.HardwareCounterBufferPtr_lock__SWIG_1(swigCPtr, this, offset, length, options.swigValue());
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SWIGTYPE_p_void lock(HardwareBuffer.LockOptions options, HardwareBuffer.UploadOptions uploadOpt) {
    long cPtr = OgreJNI.HardwareCounterBufferPtr_lock__SWIG_2(swigCPtr, this, options.swigValue(), uploadOpt.swigValue());
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SWIGTYPE_p_void lock(HardwareBuffer.LockOptions options) {
    long cPtr = OgreJNI.HardwareCounterBufferPtr_lock__SWIG_3(swigCPtr, this, options.swigValue());
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void unlock() {
    OgreJNI.HardwareCounterBufferPtr_unlock(swigCPtr, this);
  }

  public void readData(long offset, long length, SWIGTYPE_p_void pDest) {
    OgreJNI.HardwareCounterBufferPtr_readData(swigCPtr, this, offset, length, SWIGTYPE_p_void.getCPtr(pDest));
  }

  public void writeData(long offset, long length, SWIGTYPE_p_void pSource, boolean discardWholeBuffer) {
    OgreJNI.HardwareCounterBufferPtr_writeData__SWIG_0(swigCPtr, this, offset, length, SWIGTYPE_p_void.getCPtr(pSource), discardWholeBuffer);
  }

  public void writeData(long offset, long length, SWIGTYPE_p_void pSource) {
    OgreJNI.HardwareCounterBufferPtr_writeData__SWIG_1(swigCPtr, this, offset, length, SWIGTYPE_p_void.getCPtr(pSource));
  }

  public void copyData(HardwareBuffer srcBuffer, long srcOffset, long dstOffset, long length, boolean discardWholeBuffer) {
    OgreJNI.HardwareCounterBufferPtr_copyData__SWIG_0(swigCPtr, this, HardwareBuffer.getCPtr(srcBuffer), srcBuffer, srcOffset, dstOffset, length, discardWholeBuffer);
  }

  public void copyData(HardwareBuffer srcBuffer, long srcOffset, long dstOffset, long length) {
    OgreJNI.HardwareCounterBufferPtr_copyData__SWIG_1(swigCPtr, this, HardwareBuffer.getCPtr(srcBuffer), srcBuffer, srcOffset, dstOffset, length);
  }

  public void copyData(HardwareBuffer srcBuffer) {
    OgreJNI.HardwareCounterBufferPtr_copyData__SWIG_2(swigCPtr, this, HardwareBuffer.getCPtr(srcBuffer), srcBuffer);
  }

  public void _updateFromShadow() {
    OgreJNI.HardwareCounterBufferPtr__updateFromShadow(swigCPtr, this);
  }

  public long getSizeInBytes() {
    return OgreJNI.HardwareCounterBufferPtr_getSizeInBytes(swigCPtr, this);
  }

  public HardwareBuffer.Usage getUsage() {
    return HardwareBuffer.Usage.swigToEnum(OgreJNI.HardwareCounterBufferPtr_getUsage(swigCPtr, this));
  }

  public boolean isSystemMemory() {
    return OgreJNI.HardwareCounterBufferPtr_isSystemMemory(swigCPtr, this);
  }

  public boolean hasShadowBuffer() {
    return OgreJNI.HardwareCounterBufferPtr_hasShadowBuffer(swigCPtr, this);
  }

  public boolean isLocked() {
    return OgreJNI.HardwareCounterBufferPtr_isLocked(swigCPtr, this);
  }

  public void suppressHardwareUpdate(boolean suppress) {
    OgreJNI.HardwareCounterBufferPtr_suppressHardwareUpdate(swigCPtr, this, suppress);
  }

}
