/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public class HardwareCounterBuffer extends HardwareBuffer {
  private transient long swigCPtr;

  protected HardwareCounterBuffer(long cPtr, boolean cMemoryOwn) {
    super(OgreJNI.HardwareCounterBuffer_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HardwareCounterBuffer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_HardwareCounterBuffer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public HardwareBufferManagerBase getManager() {
    long cPtr = OgreJNI.HardwareCounterBuffer_getManager(swigCPtr, this);
    return (cPtr == 0) ? null : new HardwareBufferManagerBase(cPtr, false);
  }

  public String getName() {
    return OgreJNI.HardwareCounterBuffer_getName(swigCPtr, this);
  }

}
