/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public final class InstanceManagerFlags {
  public final static InstanceManagerFlags IM_USE16BIT = new InstanceManagerFlags("IM_USE16BIT", OgreJNI.IM_USE16BIT_get());
  public final static InstanceManagerFlags IM_VTFBESTFIT = new InstanceManagerFlags("IM_VTFBESTFIT", OgreJNI.IM_VTFBESTFIT_get());
  public final static InstanceManagerFlags IM_VTFBONEMATRIXLOOKUP = new InstanceManagerFlags("IM_VTFBONEMATRIXLOOKUP", OgreJNI.IM_VTFBONEMATRIXLOOKUP_get());
  public final static InstanceManagerFlags IM_USEBONEDUALQUATERNIONS = new InstanceManagerFlags("IM_USEBONEDUALQUATERNIONS", OgreJNI.IM_USEBONEDUALQUATERNIONS_get());
  public final static InstanceManagerFlags IM_USEONEWEIGHT = new InstanceManagerFlags("IM_USEONEWEIGHT", OgreJNI.IM_USEONEWEIGHT_get());
  public final static InstanceManagerFlags IM_FORCEONEWEIGHT = new InstanceManagerFlags("IM_FORCEONEWEIGHT", OgreJNI.IM_FORCEONEWEIGHT_get());
  public final static InstanceManagerFlags IM_USEALL = new InstanceManagerFlags("IM_USEALL", OgreJNI.IM_USEALL_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static InstanceManagerFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + InstanceManagerFlags.class + " with value " + swigValue);
  }

  private InstanceManagerFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private InstanceManagerFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private InstanceManagerFlags(String swigName, InstanceManagerFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static InstanceManagerFlags[] swigValues = { IM_USE16BIT, IM_VTFBESTFIT, IM_VTFBONEMATRIXLOOKUP, IM_USEBONEDUALQUATERNIONS, IM_USEONEWEIGHT, IM_FORCEONEWEIGHT, IM_USEALL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

