/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public class KeyFrame {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected KeyFrame(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(KeyFrame obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_KeyFrame(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public KeyFrame(AnimationTrack parent, float time) {
    this(OgreJNI.new_KeyFrame(AnimationTrack.getCPtr(parent), parent, time), true);
  }

  public float getTime() {
    return OgreJNI.KeyFrame_getTime(swigCPtr, this);
  }

  public KeyFrame _clone(AnimationTrack newParent) {
    long cPtr = OgreJNI.KeyFrame__clone(swigCPtr, this, AnimationTrack.getCPtr(newParent), newParent);
    return (cPtr == 0) ? null : new KeyFrame(cPtr, false);
  }

}
