/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public final class LayerBlendOperation {
  public final static LayerBlendOperation LBO_REPLACE = new LayerBlendOperation("LBO_REPLACE");
  public final static LayerBlendOperation LBO_ADD = new LayerBlendOperation("LBO_ADD");
  public final static LayerBlendOperation LBO_MODULATE = new LayerBlendOperation("LBO_MODULATE");
  public final static LayerBlendOperation LBO_ALPHA_BLEND = new LayerBlendOperation("LBO_ALPHA_BLEND");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static LayerBlendOperation swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + LayerBlendOperation.class + " with value " + swigValue);
  }

  private LayerBlendOperation(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private LayerBlendOperation(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private LayerBlendOperation(String swigName, LayerBlendOperation swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static LayerBlendOperation[] swigValues = { LBO_REPLACE, LBO_ADD, LBO_MODULATE, LBO_ALPHA_BLEND };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

