/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public final class LoggingLevel {
  public final static LoggingLevel LL_LOW = new LoggingLevel("LL_LOW", OgreJNI.LL_LOW_get());
  public final static LoggingLevel LL_NORMAL = new LoggingLevel("LL_NORMAL", OgreJNI.LL_NORMAL_get());
  public final static LoggingLevel LL_BOREME = new LoggingLevel("LL_BOREME", OgreJNI.LL_BOREME_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static LoggingLevel swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + LoggingLevel.class + " with value " + swigValue);
  }

  private LoggingLevel(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private LoggingLevel(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private LoggingLevel(String swigName, LoggingLevel swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static LoggingLevel[] swigValues = { LL_LOW, LL_NORMAL, LL_BOREME };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

