/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public class MaterialScriptProgramDefinition {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MaterialScriptProgramDefinition(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MaterialScriptProgramDefinition obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_MaterialScriptProgramDefinition(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    OgreJNI.MaterialScriptProgramDefinition_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return OgreJNI.MaterialScriptProgramDefinition_name_get(swigCPtr, this);
  }

  public void setProgType(GpuProgramType value) {
    OgreJNI.MaterialScriptProgramDefinition_progType_set(swigCPtr, this, value.swigValue());
  }

  public GpuProgramType getProgType() {
    return GpuProgramType.swigToEnum(OgreJNI.MaterialScriptProgramDefinition_progType_get(swigCPtr, this));
  }

  public void setLanguage(String value) {
    OgreJNI.MaterialScriptProgramDefinition_language_set(swigCPtr, this, value);
  }

  public String getLanguage() {
    return OgreJNI.MaterialScriptProgramDefinition_language_get(swigCPtr, this);
  }

  public void setSource(String value) {
    OgreJNI.MaterialScriptProgramDefinition_source_set(swigCPtr, this, value);
  }

  public String getSource() {
    return OgreJNI.MaterialScriptProgramDefinition_source_get(swigCPtr, this);
  }

  public void setSyntax(String value) {
    OgreJNI.MaterialScriptProgramDefinition_syntax_set(swigCPtr, this, value);
  }

  public String getSyntax() {
    return OgreJNI.MaterialScriptProgramDefinition_syntax_get(swigCPtr, this);
  }

  public void setSupportsSkeletalAnimation(boolean value) {
    OgreJNI.MaterialScriptProgramDefinition_supportsSkeletalAnimation_set(swigCPtr, this, value);
  }

  public boolean getSupportsSkeletalAnimation() {
    return OgreJNI.MaterialScriptProgramDefinition_supportsSkeletalAnimation_get(swigCPtr, this);
  }

  public void setSupportsMorphAnimation(boolean value) {
    OgreJNI.MaterialScriptProgramDefinition_supportsMorphAnimation_set(swigCPtr, this, value);
  }

  public boolean getSupportsMorphAnimation() {
    return OgreJNI.MaterialScriptProgramDefinition_supportsMorphAnimation_get(swigCPtr, this);
  }

  public void setSupportsPoseAnimation(int value) {
    OgreJNI.MaterialScriptProgramDefinition_supportsPoseAnimation_set(swigCPtr, this, value);
  }

  public int getSupportsPoseAnimation() {
    return OgreJNI.MaterialScriptProgramDefinition_supportsPoseAnimation_get(swigCPtr, this);
  }

  public void setUsesVertexTextureFetch(boolean value) {
    OgreJNI.MaterialScriptProgramDefinition_usesVertexTextureFetch_set(swigCPtr, this, value);
  }

  public boolean getUsesVertexTextureFetch() {
    return OgreJNI.MaterialScriptProgramDefinition_usesVertexTextureFetch_get(swigCPtr, this);
  }

  public void setCustomParameters(SWIGTYPE_p_Ogre__vectorT_std__pairT_std__string_std__string_t_t__type value) {
    OgreJNI.MaterialScriptProgramDefinition_customParameters_set(swigCPtr, this, SWIGTYPE_p_Ogre__vectorT_std__pairT_std__string_std__string_t_t__type.getCPtr(value));
  }

  public SWIGTYPE_p_Ogre__vectorT_std__pairT_std__string_std__string_t_t__type getCustomParameters() {
    long cPtr = OgreJNI.MaterialScriptProgramDefinition_customParameters_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Ogre__vectorT_std__pairT_std__string_std__string_t_t__type(cPtr, false);
  }

  public MaterialScriptProgramDefinition() {
    this(OgreJNI.new_MaterialScriptProgramDefinition(), true);
  }

}
