/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public class MouseMotionEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MouseMotionEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MouseMotionEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreBitesJNI.delete_MouseMotionEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(int value) {
    OgreBitesJNI.MouseMotionEvent_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return OgreBitesJNI.MouseMotionEvent_type_get(swigCPtr, this);
  }

  public void setX(int value) {
    OgreBitesJNI.MouseMotionEvent_x_set(swigCPtr, this, value);
  }

  public int getX() {
    return OgreBitesJNI.MouseMotionEvent_x_get(swigCPtr, this);
  }

  public void setY(int value) {
    OgreBitesJNI.MouseMotionEvent_y_set(swigCPtr, this, value);
  }

  public int getY() {
    return OgreBitesJNI.MouseMotionEvent_y_get(swigCPtr, this);
  }

  public void setXrel(int value) {
    OgreBitesJNI.MouseMotionEvent_xrel_set(swigCPtr, this, value);
  }

  public int getXrel() {
    return OgreBitesJNI.MouseMotionEvent_xrel_get(swigCPtr, this);
  }

  public void setYrel(int value) {
    OgreBitesJNI.MouseMotionEvent_yrel_set(swigCPtr, this, value);
  }

  public int getYrel() {
    return OgreBitesJNI.MouseMotionEvent_yrel_get(swigCPtr, this);
  }

  public void setWindowID(int value) {
    OgreBitesJNI.MouseMotionEvent_windowID_set(swigCPtr, this, value);
  }

  public int getWindowID() {
    return OgreBitesJNI.MouseMotionEvent_windowID_get(swigCPtr, this);
  }

  public MouseMotionEvent() {
    this(OgreBitesJNI.new_MouseMotionEvent(), true);
  }

}
