/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public final class OrientationMode {
  public final static OrientationMode OR_DEGREE_0 = new OrientationMode("OR_DEGREE_0", OgreJNI.OR_DEGREE_0_get());
  public final static OrientationMode OR_DEGREE_90 = new OrientationMode("OR_DEGREE_90", OgreJNI.OR_DEGREE_90_get());
  public final static OrientationMode OR_DEGREE_180 = new OrientationMode("OR_DEGREE_180", OgreJNI.OR_DEGREE_180_get());
  public final static OrientationMode OR_DEGREE_270 = new OrientationMode("OR_DEGREE_270", OgreJNI.OR_DEGREE_270_get());
  public final static OrientationMode OR_PORTRAIT = new OrientationMode("OR_PORTRAIT", OgreJNI.OR_PORTRAIT_get());
  public final static OrientationMode OR_LANDSCAPERIGHT = new OrientationMode("OR_LANDSCAPERIGHT", OgreJNI.OR_LANDSCAPERIGHT_get());
  public final static OrientationMode OR_LANDSCAPELEFT = new OrientationMode("OR_LANDSCAPELEFT", OgreJNI.OR_LANDSCAPELEFT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static OrientationMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + OrientationMode.class + " with value " + swigValue);
  }

  private OrientationMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private OrientationMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private OrientationMode(String swigName, OrientationMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static OrientationMode[] swigValues = { OR_DEGREE_0, OR_DEGREE_90, OR_DEGREE_180, OR_DEGREE_270, OR_PORTRAIT, OR_LANDSCAPERIGHT, OR_LANDSCAPELEFT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

