/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public final class PixelFormat {
  public final static PixelFormat PF_UNKNOWN = new PixelFormat("PF_UNKNOWN", OgreJNI.PF_UNKNOWN_get());
  public final static PixelFormat PF_L8 = new PixelFormat("PF_L8", OgreJNI.PF_L8_get());
  public final static PixelFormat PF_BYTE_L = new PixelFormat("PF_BYTE_L", OgreJNI.PF_BYTE_L_get());
  public final static PixelFormat PF_L16 = new PixelFormat("PF_L16", OgreJNI.PF_L16_get());
  public final static PixelFormat PF_SHORT_L = new PixelFormat("PF_SHORT_L", OgreJNI.PF_SHORT_L_get());
  public final static PixelFormat PF_A8 = new PixelFormat("PF_A8", OgreJNI.PF_A8_get());
  public final static PixelFormat PF_BYTE_A = new PixelFormat("PF_BYTE_A", OgreJNI.PF_BYTE_A_get());
  public final static PixelFormat PF_A4L4 = new PixelFormat("PF_A4L4", OgreJNI.PF_A4L4_get());
  public final static PixelFormat PF_BYTE_LA = new PixelFormat("PF_BYTE_LA", OgreJNI.PF_BYTE_LA_get());
  public final static PixelFormat PF_R5G6B5 = new PixelFormat("PF_R5G6B5", OgreJNI.PF_R5G6B5_get());
  public final static PixelFormat PF_B5G6R5 = new PixelFormat("PF_B5G6R5", OgreJNI.PF_B5G6R5_get());
  public final static PixelFormat PF_R3G3B2 = new PixelFormat("PF_R3G3B2", OgreJNI.PF_R3G3B2_get());
  public final static PixelFormat PF_A4R4G4B4 = new PixelFormat("PF_A4R4G4B4", OgreJNI.PF_A4R4G4B4_get());
  public final static PixelFormat PF_A1R5G5B5 = new PixelFormat("PF_A1R5G5B5", OgreJNI.PF_A1R5G5B5_get());
  public final static PixelFormat PF_R8G8B8 = new PixelFormat("PF_R8G8B8", OgreJNI.PF_R8G8B8_get());
  public final static PixelFormat PF_B8G8R8 = new PixelFormat("PF_B8G8R8", OgreJNI.PF_B8G8R8_get());
  public final static PixelFormat PF_A8R8G8B8 = new PixelFormat("PF_A8R8G8B8", OgreJNI.PF_A8R8G8B8_get());
  public final static PixelFormat PF_A8B8G8R8 = new PixelFormat("PF_A8B8G8R8", OgreJNI.PF_A8B8G8R8_get());
  public final static PixelFormat PF_B8G8R8A8 = new PixelFormat("PF_B8G8R8A8", OgreJNI.PF_B8G8R8A8_get());
  public final static PixelFormat PF_R8G8B8A8 = new PixelFormat("PF_R8G8B8A8", OgreJNI.PF_R8G8B8A8_get());
  public final static PixelFormat PF_X8R8G8B8 = new PixelFormat("PF_X8R8G8B8", OgreJNI.PF_X8R8G8B8_get());
  public final static PixelFormat PF_X8B8G8R8 = new PixelFormat("PF_X8B8G8R8", OgreJNI.PF_X8B8G8R8_get());
  public final static PixelFormat PF_BYTE_RGB = new PixelFormat("PF_BYTE_RGB", OgreJNI.PF_BYTE_RGB_get());
  public final static PixelFormat PF_BYTE_BGR = new PixelFormat("PF_BYTE_BGR", OgreJNI.PF_BYTE_BGR_get());
  public final static PixelFormat PF_BYTE_BGRA = new PixelFormat("PF_BYTE_BGRA", OgreJNI.PF_BYTE_BGRA_get());
  public final static PixelFormat PF_BYTE_RGBA = new PixelFormat("PF_BYTE_RGBA", OgreJNI.PF_BYTE_RGBA_get());
  public final static PixelFormat PF_A2R10G10B10 = new PixelFormat("PF_A2R10G10B10", OgreJNI.PF_A2R10G10B10_get());
  public final static PixelFormat PF_A2B10G10R10 = new PixelFormat("PF_A2B10G10R10", OgreJNI.PF_A2B10G10R10_get());
  public final static PixelFormat PF_DXT1 = new PixelFormat("PF_DXT1", OgreJNI.PF_DXT1_get());
  public final static PixelFormat PF_DXT2 = new PixelFormat("PF_DXT2", OgreJNI.PF_DXT2_get());
  public final static PixelFormat PF_DXT3 = new PixelFormat("PF_DXT3", OgreJNI.PF_DXT3_get());
  public final static PixelFormat PF_DXT4 = new PixelFormat("PF_DXT4", OgreJNI.PF_DXT4_get());
  public final static PixelFormat PF_DXT5 = new PixelFormat("PF_DXT5", OgreJNI.PF_DXT5_get());
  public final static PixelFormat PF_FLOAT16_R = new PixelFormat("PF_FLOAT16_R", OgreJNI.PF_FLOAT16_R_get());
  public final static PixelFormat PF_FLOAT16_RGB = new PixelFormat("PF_FLOAT16_RGB", OgreJNI.PF_FLOAT16_RGB_get());
  public final static PixelFormat PF_FLOAT16_RGBA = new PixelFormat("PF_FLOAT16_RGBA", OgreJNI.PF_FLOAT16_RGBA_get());
  public final static PixelFormat PF_FLOAT32_R = new PixelFormat("PF_FLOAT32_R", OgreJNI.PF_FLOAT32_R_get());
  public final static PixelFormat PF_FLOAT32_RGB = new PixelFormat("PF_FLOAT32_RGB", OgreJNI.PF_FLOAT32_RGB_get());
  public final static PixelFormat PF_FLOAT32_RGBA = new PixelFormat("PF_FLOAT32_RGBA", OgreJNI.PF_FLOAT32_RGBA_get());
  public final static PixelFormat PF_FLOAT16_GR = new PixelFormat("PF_FLOAT16_GR", OgreJNI.PF_FLOAT16_GR_get());
  public final static PixelFormat PF_FLOAT32_GR = new PixelFormat("PF_FLOAT32_GR", OgreJNI.PF_FLOAT32_GR_get());
  public final static PixelFormat PF_DEPTH = new PixelFormat("PF_DEPTH", OgreJNI.PF_DEPTH_get());
  public final static PixelFormat PF_SHORT_RGBA = new PixelFormat("PF_SHORT_RGBA", OgreJNI.PF_SHORT_RGBA_get());
  public final static PixelFormat PF_SHORT_GR = new PixelFormat("PF_SHORT_GR", OgreJNI.PF_SHORT_GR_get());
  public final static PixelFormat PF_SHORT_RGB = new PixelFormat("PF_SHORT_RGB", OgreJNI.PF_SHORT_RGB_get());
  public final static PixelFormat PF_PVRTC_RGB2 = new PixelFormat("PF_PVRTC_RGB2", OgreJNI.PF_PVRTC_RGB2_get());
  public final static PixelFormat PF_PVRTC_RGBA2 = new PixelFormat("PF_PVRTC_RGBA2", OgreJNI.PF_PVRTC_RGBA2_get());
  public final static PixelFormat PF_PVRTC_RGB4 = new PixelFormat("PF_PVRTC_RGB4", OgreJNI.PF_PVRTC_RGB4_get());
  public final static PixelFormat PF_PVRTC_RGBA4 = new PixelFormat("PF_PVRTC_RGBA4", OgreJNI.PF_PVRTC_RGBA4_get());
  public final static PixelFormat PF_PVRTC2_2BPP = new PixelFormat("PF_PVRTC2_2BPP", OgreJNI.PF_PVRTC2_2BPP_get());
  public final static PixelFormat PF_PVRTC2_4BPP = new PixelFormat("PF_PVRTC2_4BPP", OgreJNI.PF_PVRTC2_4BPP_get());
  public final static PixelFormat PF_R11G11B10_FLOAT = new PixelFormat("PF_R11G11B10_FLOAT", OgreJNI.PF_R11G11B10_FLOAT_get());
  public final static PixelFormat PF_R8_UINT = new PixelFormat("PF_R8_UINT", OgreJNI.PF_R8_UINT_get());
  public final static PixelFormat PF_R8G8_UINT = new PixelFormat("PF_R8G8_UINT", OgreJNI.PF_R8G8_UINT_get());
  public final static PixelFormat PF_R8G8B8_UINT = new PixelFormat("PF_R8G8B8_UINT", OgreJNI.PF_R8G8B8_UINT_get());
  public final static PixelFormat PF_R8G8B8A8_UINT = new PixelFormat("PF_R8G8B8A8_UINT", OgreJNI.PF_R8G8B8A8_UINT_get());
  public final static PixelFormat PF_R16_UINT = new PixelFormat("PF_R16_UINT", OgreJNI.PF_R16_UINT_get());
  public final static PixelFormat PF_R16G16_UINT = new PixelFormat("PF_R16G16_UINT", OgreJNI.PF_R16G16_UINT_get());
  public final static PixelFormat PF_R16G16B16_UINT = new PixelFormat("PF_R16G16B16_UINT", OgreJNI.PF_R16G16B16_UINT_get());
  public final static PixelFormat PF_R16G16B16A16_UINT = new PixelFormat("PF_R16G16B16A16_UINT", OgreJNI.PF_R16G16B16A16_UINT_get());
  public final static PixelFormat PF_R32_UINT = new PixelFormat("PF_R32_UINT", OgreJNI.PF_R32_UINT_get());
  public final static PixelFormat PF_R32G32_UINT = new PixelFormat("PF_R32G32_UINT", OgreJNI.PF_R32G32_UINT_get());
  public final static PixelFormat PF_R32G32B32_UINT = new PixelFormat("PF_R32G32B32_UINT", OgreJNI.PF_R32G32B32_UINT_get());
  public final static PixelFormat PF_R32G32B32A32_UINT = new PixelFormat("PF_R32G32B32A32_UINT", OgreJNI.PF_R32G32B32A32_UINT_get());
  public final static PixelFormat PF_R8_SINT = new PixelFormat("PF_R8_SINT", OgreJNI.PF_R8_SINT_get());
  public final static PixelFormat PF_R8G8_SINT = new PixelFormat("PF_R8G8_SINT", OgreJNI.PF_R8G8_SINT_get());
  public final static PixelFormat PF_R8G8B8_SINT = new PixelFormat("PF_R8G8B8_SINT", OgreJNI.PF_R8G8B8_SINT_get());
  public final static PixelFormat PF_R8G8B8A8_SINT = new PixelFormat("PF_R8G8B8A8_SINT", OgreJNI.PF_R8G8B8A8_SINT_get());
  public final static PixelFormat PF_R16_SINT = new PixelFormat("PF_R16_SINT", OgreJNI.PF_R16_SINT_get());
  public final static PixelFormat PF_R16G16_SINT = new PixelFormat("PF_R16G16_SINT", OgreJNI.PF_R16G16_SINT_get());
  public final static PixelFormat PF_R16G16B16_SINT = new PixelFormat("PF_R16G16B16_SINT", OgreJNI.PF_R16G16B16_SINT_get());
  public final static PixelFormat PF_R16G16B16A16_SINT = new PixelFormat("PF_R16G16B16A16_SINT", OgreJNI.PF_R16G16B16A16_SINT_get());
  public final static PixelFormat PF_R32_SINT = new PixelFormat("PF_R32_SINT", OgreJNI.PF_R32_SINT_get());
  public final static PixelFormat PF_R32G32_SINT = new PixelFormat("PF_R32G32_SINT", OgreJNI.PF_R32G32_SINT_get());
  public final static PixelFormat PF_R32G32B32_SINT = new PixelFormat("PF_R32G32B32_SINT", OgreJNI.PF_R32G32B32_SINT_get());
  public final static PixelFormat PF_R32G32B32A32_SINT = new PixelFormat("PF_R32G32B32A32_SINT", OgreJNI.PF_R32G32B32A32_SINT_get());
  public final static PixelFormat PF_R9G9B9E5_SHAREDEXP = new PixelFormat("PF_R9G9B9E5_SHAREDEXP", OgreJNI.PF_R9G9B9E5_SHAREDEXP_get());
  public final static PixelFormat PF_BC4_UNORM = new PixelFormat("PF_BC4_UNORM", OgreJNI.PF_BC4_UNORM_get());
  public final static PixelFormat PF_BC4_SNORM = new PixelFormat("PF_BC4_SNORM", OgreJNI.PF_BC4_SNORM_get());
  public final static PixelFormat PF_BC5_UNORM = new PixelFormat("PF_BC5_UNORM", OgreJNI.PF_BC5_UNORM_get());
  public final static PixelFormat PF_BC5_SNORM = new PixelFormat("PF_BC5_SNORM", OgreJNI.PF_BC5_SNORM_get());
  public final static PixelFormat PF_BC6H_UF16 = new PixelFormat("PF_BC6H_UF16", OgreJNI.PF_BC6H_UF16_get());
  public final static PixelFormat PF_BC6H_SF16 = new PixelFormat("PF_BC6H_SF16", OgreJNI.PF_BC6H_SF16_get());
  public final static PixelFormat PF_BC7_UNORM = new PixelFormat("PF_BC7_UNORM", OgreJNI.PF_BC7_UNORM_get());
  public final static PixelFormat PF_BC7_UNORM_SRGB = new PixelFormat("PF_BC7_UNORM_SRGB", OgreJNI.PF_BC7_UNORM_SRGB_get());
  public final static PixelFormat PF_R8 = new PixelFormat("PF_R8", OgreJNI.PF_R8_get());
  public final static PixelFormat PF_RG8 = new PixelFormat("PF_RG8", OgreJNI.PF_RG8_get());
  public final static PixelFormat PF_R8_SNORM = new PixelFormat("PF_R8_SNORM", OgreJNI.PF_R8_SNORM_get());
  public final static PixelFormat PF_R8G8_SNORM = new PixelFormat("PF_R8G8_SNORM", OgreJNI.PF_R8G8_SNORM_get());
  public final static PixelFormat PF_R8G8B8_SNORM = new PixelFormat("PF_R8G8B8_SNORM", OgreJNI.PF_R8G8B8_SNORM_get());
  public final static PixelFormat PF_R8G8B8A8_SNORM = new PixelFormat("PF_R8G8B8A8_SNORM", OgreJNI.PF_R8G8B8A8_SNORM_get());
  public final static PixelFormat PF_R16_SNORM = new PixelFormat("PF_R16_SNORM", OgreJNI.PF_R16_SNORM_get());
  public final static PixelFormat PF_R16G16_SNORM = new PixelFormat("PF_R16G16_SNORM", OgreJNI.PF_R16G16_SNORM_get());
  public final static PixelFormat PF_R16G16B16_SNORM = new PixelFormat("PF_R16G16B16_SNORM", OgreJNI.PF_R16G16B16_SNORM_get());
  public final static PixelFormat PF_R16G16B16A16_SNORM = new PixelFormat("PF_R16G16B16A16_SNORM", OgreJNI.PF_R16G16B16A16_SNORM_get());
  public final static PixelFormat PF_ETC1_RGB8 = new PixelFormat("PF_ETC1_RGB8", OgreJNI.PF_ETC1_RGB8_get());
  public final static PixelFormat PF_ETC2_RGB8 = new PixelFormat("PF_ETC2_RGB8", OgreJNI.PF_ETC2_RGB8_get());
  public final static PixelFormat PF_ETC2_RGBA8 = new PixelFormat("PF_ETC2_RGBA8", OgreJNI.PF_ETC2_RGBA8_get());
  public final static PixelFormat PF_ETC2_RGB8A1 = new PixelFormat("PF_ETC2_RGB8A1", OgreJNI.PF_ETC2_RGB8A1_get());
  public final static PixelFormat PF_ATC_RGB = new PixelFormat("PF_ATC_RGB", OgreJNI.PF_ATC_RGB_get());
  public final static PixelFormat PF_ATC_RGBA_EXPLICIT_ALPHA = new PixelFormat("PF_ATC_RGBA_EXPLICIT_ALPHA", OgreJNI.PF_ATC_RGBA_EXPLICIT_ALPHA_get());
  public final static PixelFormat PF_ATC_RGBA_INTERPOLATED_ALPHA = new PixelFormat("PF_ATC_RGBA_INTERPOLATED_ALPHA", OgreJNI.PF_ATC_RGBA_INTERPOLATED_ALPHA_get());
  public final static PixelFormat PF_ASTC_RGBA_4X4_LDR = new PixelFormat("PF_ASTC_RGBA_4X4_LDR", OgreJNI.PF_ASTC_RGBA_4X4_LDR_get());
  public final static PixelFormat PF_ASTC_RGBA_5X4_LDR = new PixelFormat("PF_ASTC_RGBA_5X4_LDR", OgreJNI.PF_ASTC_RGBA_5X4_LDR_get());
  public final static PixelFormat PF_ASTC_RGBA_5X5_LDR = new PixelFormat("PF_ASTC_RGBA_5X5_LDR", OgreJNI.PF_ASTC_RGBA_5X5_LDR_get());
  public final static PixelFormat PF_ASTC_RGBA_6X5_LDR = new PixelFormat("PF_ASTC_RGBA_6X5_LDR", OgreJNI.PF_ASTC_RGBA_6X5_LDR_get());
  public final static PixelFormat PF_ASTC_RGBA_6X6_LDR = new PixelFormat("PF_ASTC_RGBA_6X6_LDR", OgreJNI.PF_ASTC_RGBA_6X6_LDR_get());
  public final static PixelFormat PF_ASTC_RGBA_8X5_LDR = new PixelFormat("PF_ASTC_RGBA_8X5_LDR", OgreJNI.PF_ASTC_RGBA_8X5_LDR_get());
  public final static PixelFormat PF_ASTC_RGBA_8X6_LDR = new PixelFormat("PF_ASTC_RGBA_8X6_LDR", OgreJNI.PF_ASTC_RGBA_8X6_LDR_get());
  public final static PixelFormat PF_ASTC_RGBA_8X8_LDR = new PixelFormat("PF_ASTC_RGBA_8X8_LDR", OgreJNI.PF_ASTC_RGBA_8X8_LDR_get());
  public final static PixelFormat PF_ASTC_RGBA_10X5_LDR = new PixelFormat("PF_ASTC_RGBA_10X5_LDR", OgreJNI.PF_ASTC_RGBA_10X5_LDR_get());
  public final static PixelFormat PF_ASTC_RGBA_10X6_LDR = new PixelFormat("PF_ASTC_RGBA_10X6_LDR", OgreJNI.PF_ASTC_RGBA_10X6_LDR_get());
  public final static PixelFormat PF_ASTC_RGBA_10X8_LDR = new PixelFormat("PF_ASTC_RGBA_10X8_LDR", OgreJNI.PF_ASTC_RGBA_10X8_LDR_get());
  public final static PixelFormat PF_ASTC_RGBA_10X10_LDR = new PixelFormat("PF_ASTC_RGBA_10X10_LDR", OgreJNI.PF_ASTC_RGBA_10X10_LDR_get());
  public final static PixelFormat PF_ASTC_RGBA_12X10_LDR = new PixelFormat("PF_ASTC_RGBA_12X10_LDR", OgreJNI.PF_ASTC_RGBA_12X10_LDR_get());
  public final static PixelFormat PF_ASTC_RGBA_12X12_LDR = new PixelFormat("PF_ASTC_RGBA_12X12_LDR", OgreJNI.PF_ASTC_RGBA_12X12_LDR_get());
  public final static PixelFormat PF_COUNT = new PixelFormat("PF_COUNT", OgreJNI.PF_COUNT_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static PixelFormat swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + PixelFormat.class + " with value " + swigValue);
  }

  private PixelFormat(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private PixelFormat(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private PixelFormat(String swigName, PixelFormat swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static PixelFormat[] swigValues = { PF_UNKNOWN, PF_L8, PF_BYTE_L, PF_L16, PF_SHORT_L, PF_A8, PF_BYTE_A, PF_A4L4, PF_BYTE_LA, PF_R5G6B5, PF_B5G6R5, PF_R3G3B2, PF_A4R4G4B4, PF_A1R5G5B5, PF_R8G8B8, PF_B8G8R8, PF_A8R8G8B8, PF_A8B8G8R8, PF_B8G8R8A8, PF_R8G8B8A8, PF_X8R8G8B8, PF_X8B8G8R8, PF_BYTE_RGB, PF_BYTE_BGR, PF_BYTE_BGRA, PF_BYTE_RGBA, PF_A2R10G10B10, PF_A2B10G10R10, PF_DXT1, PF_DXT2, PF_DXT3, PF_DXT4, PF_DXT5, PF_FLOAT16_R, PF_FLOAT16_RGB, PF_FLOAT16_RGBA, PF_FLOAT32_R, PF_FLOAT32_RGB, PF_FLOAT32_RGBA, PF_FLOAT16_GR, PF_FLOAT32_GR, PF_DEPTH, PF_SHORT_RGBA, PF_SHORT_GR, PF_SHORT_RGB, PF_PVRTC_RGB2, PF_PVRTC_RGBA2, PF_PVRTC_RGB4, PF_PVRTC_RGBA4, PF_PVRTC2_2BPP, PF_PVRTC2_4BPP, PF_R11G11B10_FLOAT, PF_R8_UINT, PF_R8G8_UINT, PF_R8G8B8_UINT, PF_R8G8B8A8_UINT, PF_R16_UINT, PF_R16G16_UINT, PF_R16G16B16_UINT, PF_R16G16B16A16_UINT, PF_R32_UINT, PF_R32G32_UINT, PF_R32G32B32_UINT, PF_R32G32B32A32_UINT, PF_R8_SINT, PF_R8G8_SINT, PF_R8G8B8_SINT, PF_R8G8B8A8_SINT, PF_R16_SINT, PF_R16G16_SINT, PF_R16G16B16_SINT, PF_R16G16B16A16_SINT, PF_R32_SINT, PF_R32G32_SINT, PF_R32G32B32_SINT, PF_R32G32B32A32_SINT, PF_R9G9B9E5_SHAREDEXP, PF_BC4_UNORM, PF_BC4_SNORM, PF_BC5_UNORM, PF_BC5_SNORM, PF_BC6H_UF16, PF_BC6H_SF16, PF_BC7_UNORM, PF_BC7_UNORM_SRGB, PF_R8, PF_RG8, PF_R8_SNORM, PF_R8G8_SNORM, PF_R8G8B8_SNORM, PF_R8G8B8A8_SNORM, PF_R16_SNORM, PF_R16G16_SNORM, PF_R16G16B16_SNORM, PF_R16G16B16A16_SNORM, PF_ETC1_RGB8, PF_ETC2_RGB8, PF_ETC2_RGBA8, PF_ETC2_RGB8A1, PF_ATC_RGB, PF_ATC_RGBA_EXPLICIT_ALPHA, PF_ATC_RGBA_INTERPOLATED_ALPHA, PF_ASTC_RGBA_4X4_LDR, PF_ASTC_RGBA_5X4_LDR, PF_ASTC_RGBA_5X5_LDR, PF_ASTC_RGBA_6X5_LDR, PF_ASTC_RGBA_6X6_LDR, PF_ASTC_RGBA_8X5_LDR, PF_ASTC_RGBA_8X6_LDR, PF_ASTC_RGBA_8X8_LDR, PF_ASTC_RGBA_10X5_LDR, PF_ASTC_RGBA_10X6_LDR, PF_ASTC_RGBA_10X8_LDR, PF_ASTC_RGBA_10X10_LDR, PF_ASTC_RGBA_12X10_LDR, PF_ASTC_RGBA_12X12_LDR, PF_COUNT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

