/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public final class ProjectionType {
  public final static ProjectionType PT_ORTHOGRAPHIC = new ProjectionType("PT_ORTHOGRAPHIC");
  public final static ProjectionType PT_PERSPECTIVE = new ProjectionType("PT_PERSPECTIVE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ProjectionType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ProjectionType.class + " with value " + swigValue);
  }

  private ProjectionType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ProjectionType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ProjectionType(String swigName, ProjectionType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ProjectionType[] swigValues = { PT_ORTHOGRAPHIC, PT_PERSPECTIVE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

