/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public class RenderablePass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RenderablePass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RenderablePass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_RenderablePass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRenderable(Renderable value) {
    OgreJNI.RenderablePass_renderable_set(swigCPtr, this, Renderable.getCPtr(value), value);
  }

  public Renderable getRenderable() {
    long cPtr = OgreJNI.RenderablePass_renderable_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Renderable(cPtr, false);
  }

  public void setPass(Pass value) {
    OgreJNI.RenderablePass_pass_set(swigCPtr, this, Pass.getCPtr(value), value);
  }

  public Pass getPass() {
    long cPtr = OgreJNI.RenderablePass_pass_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Pass(cPtr, false);
  }

  public RenderablePass(Renderable rend, Pass p) {
    this(OgreJNI.new_RenderablePass(Renderable.getCPtr(rend), rend, Pass.getCPtr(p), p), true);
  }

}
