/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public class RenderTargetEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RenderTargetEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RenderTargetEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_RenderTargetEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSource(RenderTarget value) {
    OgreJNI.RenderTargetEvent_source_set(swigCPtr, this, RenderTarget.getCPtr(value), value);
  }

  public RenderTarget getSource() {
    long cPtr = OgreJNI.RenderTargetEvent_source_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RenderTarget(cPtr, false);
  }

  public RenderTargetEvent() {
    this(OgreJNI.new_RenderTargetEvent(), true);
  }

}
