/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public class ResourceGroupListener {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ResourceGroupListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ResourceGroupListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_ResourceGroupListener(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void resourceGroupScriptingStarted(String groupName, long scriptCount) {
    OgreJNI.ResourceGroupListener_resourceGroupScriptingStarted(swigCPtr, this, groupName, scriptCount);
  }

  public void scriptParseStarted(String scriptName, SWIGTYPE_p_bool skipThisScript) {
    OgreJNI.ResourceGroupListener_scriptParseStarted(swigCPtr, this, scriptName, SWIGTYPE_p_bool.getCPtr(skipThisScript));
  }

  public void scriptParseEnded(String scriptName, boolean skipped) {
    OgreJNI.ResourceGroupListener_scriptParseEnded(swigCPtr, this, scriptName, skipped);
  }

  public void resourceGroupScriptingEnded(String groupName) {
    OgreJNI.ResourceGroupListener_resourceGroupScriptingEnded(swigCPtr, this, groupName);
  }

  public void resourceGroupPrepareStarted(String groupName, long resourceCount) {
    OgreJNI.ResourceGroupListener_resourceGroupPrepareStarted(swigCPtr, this, groupName, resourceCount);
  }

  public void resourcePrepareStarted(ResourcePtr resource) {
    OgreJNI.ResourceGroupListener_resourcePrepareStarted(swigCPtr, this, ResourcePtr.getCPtr(resource), resource);
  }

  public void resourcePrepareEnded() {
    OgreJNI.ResourceGroupListener_resourcePrepareEnded(swigCPtr, this);
  }

  public void worldGeometryPrepareStageStarted(String description) {
    OgreJNI.ResourceGroupListener_worldGeometryPrepareStageStarted(swigCPtr, this, description);
  }

  public void worldGeometryPrepareStageEnded() {
    OgreJNI.ResourceGroupListener_worldGeometryPrepareStageEnded(swigCPtr, this);
  }

  public void resourceGroupPrepareEnded(String groupName) {
    OgreJNI.ResourceGroupListener_resourceGroupPrepareEnded(swigCPtr, this, groupName);
  }

  public void resourceGroupLoadStarted(String groupName, long resourceCount) {
    OgreJNI.ResourceGroupListener_resourceGroupLoadStarted(swigCPtr, this, groupName, resourceCount);
  }

  public void resourceLoadStarted(ResourcePtr resource) {
    OgreJNI.ResourceGroupListener_resourceLoadStarted(swigCPtr, this, ResourcePtr.getCPtr(resource), resource);
  }

  public void resourceLoadEnded() {
    OgreJNI.ResourceGroupListener_resourceLoadEnded(swigCPtr, this);
  }

  public void worldGeometryStageStarted(String description) {
    OgreJNI.ResourceGroupListener_worldGeometryStageStarted(swigCPtr, this, description);
  }

  public void worldGeometryStageEnded() {
    OgreJNI.ResourceGroupListener_worldGeometryStageEnded(swigCPtr, this);
  }

  public void resourceGroupLoadEnded(String groupName) {
    OgreJNI.ResourceGroupListener_resourceGroupLoadEnded(swigCPtr, this, groupName);
  }

  public void resourceCreated(ResourcePtr resource) {
    OgreJNI.ResourceGroupListener_resourceCreated(swigCPtr, this, ResourcePtr.getCPtr(resource), resource);
  }

  public void resourceRemove(ResourcePtr resource) {
    OgreJNI.ResourceGroupListener_resourceRemove(swigCPtr, this, ResourcePtr.getCPtr(resource), resource);
  }

  public ResourceGroupListener() {
    this(OgreJNI.new_ResourceGroupListener(), true);
  }

}
