/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public class ResourceManager extends ScriptLoader {
  private transient long swigCPtr;

  protected ResourceManager(long cPtr, boolean cMemoryOwn) {
    super(OgreJNI.ResourceManager_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ResourceManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_ResourceManager(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ResourcePtr createResource(String name, String group, boolean isManual, ManualResourceLoader loader, SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t createParams) {
    return new ResourcePtr(OgreJNI.ResourceManager_createResource__SWIG_0(swigCPtr, this, name, group, isManual, ManualResourceLoader.getCPtr(loader), loader, SWIGTYPE_p_std__mapT_std__string_std__string_std__lessT_std__string_t_t.getCPtr(createParams)), true);
  }

  public ResourcePtr createResource(String name, String group, boolean isManual, ManualResourceLoader loader) {
    return new ResourcePtr(OgreJNI.ResourceManager_createResource__SWIG_1(swigCPtr, this, name, group, isManual, ManualResourceLoader.getCPtr(loader), loader), true);
  }

  public ResourcePtr createResource(String name, String group, boolean isManual) {
    return new ResourcePtr(OgreJNI.ResourceManager_createResource__SWIG_2(swigCPtr, this, name, group, isManual), true);
  }

  public ResourcePtr createResource(String name, String group) {
    return new ResourcePtr(OgreJNI.ResourceManager_createResource__SWIG_3(swigCPtr, this, name, group), true);
  }

  public void setMemoryBudget(long bytes) {
    OgreJNI.ResourceManager_setMemoryBudget(swigCPtr, this, bytes);
  }

  public long getMemoryBudget() {
    return OgreJNI.ResourceManager_getMemoryBudget(swigCPtr, this);
  }

  public long getMemoryUsage() {
    return OgreJNI.ResourceManager_getMemoryUsage(swigCPtr, this);
  }

  public void unload(String name, String group) {
    OgreJNI.ResourceManager_unload__SWIG_0(swigCPtr, this, name, group);
  }

  public void unload(java.math.BigInteger handle) {
    OgreJNI.ResourceManager_unload__SWIG_1(swigCPtr, this, handle);
  }

  public void unloadAll(boolean reloadableOnly) {
    OgreJNI.ResourceManager_unloadAll__SWIG_0(swigCPtr, this, reloadableOnly);
  }

  public void unloadAll() {
    OgreJNI.ResourceManager_unloadAll__SWIG_1(swigCPtr, this);
  }

  public void reloadAll(boolean reloadableOnly) {
    OgreJNI.ResourceManager_reloadAll__SWIG_0(swigCPtr, this, reloadableOnly);
  }

  public void reloadAll() {
    OgreJNI.ResourceManager_reloadAll__SWIG_1(swigCPtr, this);
  }

  public void unloadUnreferencedResources(boolean reloadableOnly) {
    OgreJNI.ResourceManager_unloadUnreferencedResources__SWIG_0(swigCPtr, this, reloadableOnly);
  }

  public void unloadUnreferencedResources() {
    OgreJNI.ResourceManager_unloadUnreferencedResources__SWIG_1(swigCPtr, this);
  }

  public void reloadUnreferencedResources(boolean reloadableOnly) {
    OgreJNI.ResourceManager_reloadUnreferencedResources__SWIG_0(swigCPtr, this, reloadableOnly);
  }

  public void reloadUnreferencedResources() {
    OgreJNI.ResourceManager_reloadUnreferencedResources__SWIG_1(swigCPtr, this);
  }

  public void unloadAll(Resource.LoadingFlags flags) {
    OgreJNI.ResourceManager_unloadAll__SWIG_2(swigCPtr, this, flags.swigValue());
  }

  public void reloadAll(Resource.LoadingFlags flags) {
    OgreJNI.ResourceManager_reloadAll__SWIG_2(swigCPtr, this, flags.swigValue());
  }

  public void remove(ResourcePtr r) {
    OgreJNI.ResourceManager_remove__SWIG_0(swigCPtr, this, ResourcePtr.getCPtr(r), r);
  }

  public void remove(String name, String group) {
    OgreJNI.ResourceManager_remove__SWIG_1(swigCPtr, this, name, group);
  }

  public void remove(java.math.BigInteger handle) {
    OgreJNI.ResourceManager_remove__SWIG_2(swigCPtr, this, handle);
  }

  public void removeAll() {
    OgreJNI.ResourceManager_removeAll(swigCPtr, this);
  }

  public void removeUnreferencedResources(boolean reloadableOnly) {
    OgreJNI.ResourceManager_removeUnreferencedResources__SWIG_0(swigCPtr, this, reloadableOnly);
  }

  public void removeUnreferencedResources() {
    OgreJNI.ResourceManager_removeUnreferencedResources__SWIG_1(swigCPtr, this);
  }

  public ResourcePtr getByHandle(java.math.BigInteger handle) {
    return new ResourcePtr(OgreJNI.ResourceManager_getByHandle(swigCPtr, this, handle), true);
  }

  public boolean resourceExists(String name, String group) {
    return OgreJNI.ResourceManager_resourceExists__SWIG_0(swigCPtr, this, name, group);
  }

  public boolean resourceExists(java.math.BigInteger handle) {
    return OgreJNI.ResourceManager_resourceExists__SWIG_1(swigCPtr, this, handle);
  }

  public void _notifyResourceTouched(Resource res) {
    OgreJNI.ResourceManager__notifyResourceTouched(swigCPtr, this, Resource.getCPtr(res), res);
  }

  public void _notifyResourceLoaded(Resource res) {
    OgreJNI.ResourceManager__notifyResourceLoaded(swigCPtr, this, Resource.getCPtr(res), res);
  }

  public void _notifyResourceUnloaded(Resource res) {
    OgreJNI.ResourceManager__notifyResourceUnloaded(swigCPtr, this, Resource.getCPtr(res), res);
  }

  public StringVector getScriptPatterns() {
    return new StringVector(OgreJNI.ResourceManager_getScriptPatterns(swigCPtr, this), false);
  }

  public void parseScript(SWIGTYPE_p_Ogre__SharedPtrT_Ogre__DataStream_t stream, String groupName) {
    OgreJNI.ResourceManager_parseScript(swigCPtr, this, SWIGTYPE_p_Ogre__SharedPtrT_Ogre__DataStream_t.getCPtr(stream), groupName);
  }

  public float getLoadingOrder() {
    return OgreJNI.ResourceManager_getLoadingOrder(swigCPtr, this);
  }

  public String getResourceType() {
    return OgreJNI.ResourceManager_getResourceType(swigCPtr, this);
  }

  public void setVerbose(boolean v) {
    OgreJNI.ResourceManager_setVerbose(swigCPtr, this, v);
  }

  public boolean getVerbose() {
    return OgreJNI.ResourceManager_getVerbose(swigCPtr, this);
  }

  static public class ResourcePool {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected ResourcePool(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(ResourcePool obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OgreJNI.delete_ResourceManager_ResourcePool(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    public ResourcePool(String name) {
      this(OgreJNI.new_ResourceManager_ResourcePool(name), true);
    }
  
    public String getName() {
      return OgreJNI.ResourceManager_ResourcePool_getName(swigCPtr, this);
    }
  
    public void clear() {
      OgreJNI.ResourceManager_ResourcePool_clear(swigCPtr, this);
    }
  
  }

  public ResourceManager.ResourcePool getResourcePool(String name) {
    long cPtr = OgreJNI.ResourceManager_getResourcePool(swigCPtr, this, name);
    return (cPtr == 0) ? null : new ResourceManager.ResourcePool(cPtr, false);
  }

  public void destroyResourcePool(ResourceManager.ResourcePool pool) {
    OgreJNI.ResourceManager_destroyResourcePool__SWIG_0(swigCPtr, this, ResourceManager.ResourcePool.getCPtr(pool), pool);
  }

  public void destroyResourcePool(String name) {
    OgreJNI.ResourceManager_destroyResourcePool__SWIG_1(swigCPtr, this, name);
  }

  public void destroyAllResourcePools() {
    OgreJNI.ResourceManager_destroyAllResourcePools(swigCPtr, this);
  }

  public SWIGTYPE_p_Ogre__MapIteratorT_Ogre__mapT_unsigned_long_long_Ogre__SharedPtrT_Ogre__Resource_t_std__lessT_unsigned_long_long_t_t__type_t getResourceIterator() {
    return new SWIGTYPE_p_Ogre__MapIteratorT_Ogre__mapT_unsigned_long_long_Ogre__SharedPtrT_Ogre__Resource_t_std__lessT_unsigned_long_long_t_t__type_t(OgreJNI.ResourceManager_getResourceIterator(swigCPtr, this), true);
  }

}
