/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public class SceneManagerFactory {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SceneManagerFactory(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SceneManagerFactory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_SceneManagerFactory(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SceneManagerMetaData getMetaData() {
    return new SceneManagerMetaData(OgreJNI.SceneManagerFactory_getMetaData(swigCPtr, this), false);
  }

  public SceneManager createInstance(String instanceName) {
    long cPtr = OgreJNI.SceneManagerFactory_createInstance(swigCPtr, this, instanceName);
    return (cPtr == 0) ? null : new SceneManager(cPtr, false);
  }

  public void destroyInstance(SceneManager instance) {
    OgreJNI.SceneManagerFactory_destroyInstance(swigCPtr, this, SceneManager.getCPtr(instance), instance);
  }

}
