/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public class SceneManagerMetaData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SceneManagerMetaData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SceneManagerMetaData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_SceneManagerMetaData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTypeName(String value) {
    OgreJNI.SceneManagerMetaData_typeName_set(swigCPtr, this, value);
  }

  public String getTypeName() {
    return OgreJNI.SceneManagerMetaData_typeName_get(swigCPtr, this);
  }

  public void setDescription(String value) {
    OgreJNI.SceneManagerMetaData_description_set(swigCPtr, this, value);
  }

  public String getDescription() {
    return OgreJNI.SceneManagerMetaData_description_get(swigCPtr, this);
  }

  public void setSceneTypeMask(int value) {
    OgreJNI.SceneManagerMetaData_sceneTypeMask_set(swigCPtr, this, value);
  }

  public int getSceneTypeMask() {
    return OgreJNI.SceneManagerMetaData_sceneTypeMask_get(swigCPtr, this);
  }

  public void setWorldGeometrySupported(boolean value) {
    OgreJNI.SceneManagerMetaData_worldGeometrySupported_set(swigCPtr, this, value);
  }

  public boolean getWorldGeometrySupported() {
    return OgreJNI.SceneManagerMetaData_worldGeometrySupported_get(swigCPtr, this);
  }

  public SceneManagerMetaData() {
    this(OgreJNI.new_SceneManagerMetaData(), true);
  }

}
