/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public class ScriptCompiler {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ScriptCompiler(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ScriptCompiler obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_ScriptCompiler(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  static public class Error {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Error(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Error obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OgreJNI.delete_ScriptCompiler_Error(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    public void setFile(String value) {
      OgreJNI.ScriptCompiler_Error_file_set(swigCPtr, this, value);
    }
  
    public String getFile() {
      return OgreJNI.ScriptCompiler_Error_file_get(swigCPtr, this);
    }
  
    public void setMessage(String value) {
      OgreJNI.ScriptCompiler_Error_message_set(swigCPtr, this, value);
    }
  
    public String getMessage() {
      return OgreJNI.ScriptCompiler_Error_message_get(swigCPtr, this);
    }
  
    public void setLine(int value) {
      OgreJNI.ScriptCompiler_Error_line_set(swigCPtr, this, value);
    }
  
    public int getLine() {
      return OgreJNI.ScriptCompiler_Error_line_get(swigCPtr, this);
    }
  
    public void setCode(long value) {
      OgreJNI.ScriptCompiler_Error_code_set(swigCPtr, this, value);
    }
  
    public long getCode() {
      return OgreJNI.ScriptCompiler_Error_code_get(swigCPtr, this);
    }
  
    public Error() {
      this(OgreJNI.new_ScriptCompiler_Error(), true);
    }
  
  }

  public static String formatErrorCode(long code) {
    return OgreJNI.ScriptCompiler_formatErrorCode(code);
  }

  public ScriptCompiler() {
    this(OgreJNI.new_ScriptCompiler(), true);
  }

  public boolean compile(String str, String source, String group) {
    return OgreJNI.ScriptCompiler_compile__SWIG_0(swigCPtr, this, str, source, group);
  }

  public boolean compile(SWIGTYPE_p_Ogre__SharedPtrT_Ogre__listT_Ogre__SharedPtrT_Ogre__ConcreteNode_t_t__type_t nodes, String group) {
    return OgreJNI.ScriptCompiler_compile__SWIG_1(swigCPtr, this, SWIGTYPE_p_Ogre__SharedPtrT_Ogre__listT_Ogre__SharedPtrT_Ogre__ConcreteNode_t_t__type_t.getCPtr(nodes), group);
  }

  public SWIGTYPE_p_Ogre__SharedPtrT_Ogre__listT_Ogre__SharedPtrT_Ogre__AbstractNode_t_t__type_t _generateAST(String str, String source, boolean doImports, boolean doObjects, boolean doVariables) {
    return new SWIGTYPE_p_Ogre__SharedPtrT_Ogre__listT_Ogre__SharedPtrT_Ogre__AbstractNode_t_t__type_t(OgreJNI.ScriptCompiler__generateAST__SWIG_0(swigCPtr, this, str, source, doImports, doObjects, doVariables), true);
  }

  public SWIGTYPE_p_Ogre__SharedPtrT_Ogre__listT_Ogre__SharedPtrT_Ogre__AbstractNode_t_t__type_t _generateAST(String str, String source, boolean doImports, boolean doObjects) {
    return new SWIGTYPE_p_Ogre__SharedPtrT_Ogre__listT_Ogre__SharedPtrT_Ogre__AbstractNode_t_t__type_t(OgreJNI.ScriptCompiler__generateAST__SWIG_1(swigCPtr, this, str, source, doImports, doObjects), true);
  }

  public SWIGTYPE_p_Ogre__SharedPtrT_Ogre__listT_Ogre__SharedPtrT_Ogre__AbstractNode_t_t__type_t _generateAST(String str, String source, boolean doImports) {
    return new SWIGTYPE_p_Ogre__SharedPtrT_Ogre__listT_Ogre__SharedPtrT_Ogre__AbstractNode_t_t__type_t(OgreJNI.ScriptCompiler__generateAST__SWIG_2(swigCPtr, this, str, source, doImports), true);
  }

  public SWIGTYPE_p_Ogre__SharedPtrT_Ogre__listT_Ogre__SharedPtrT_Ogre__AbstractNode_t_t__type_t _generateAST(String str, String source) {
    return new SWIGTYPE_p_Ogre__SharedPtrT_Ogre__listT_Ogre__SharedPtrT_Ogre__AbstractNode_t_t__type_t(OgreJNI.ScriptCompiler__generateAST__SWIG_3(swigCPtr, this, str, source), true);
  }

  public boolean _compile(SWIGTYPE_p_Ogre__SharedPtrT_Ogre__listT_Ogre__SharedPtrT_Ogre__AbstractNode_t_t__type_t nodes, String group, boolean doImports, boolean doObjects, boolean doVariables) {
    return OgreJNI.ScriptCompiler__compile__SWIG_0(swigCPtr, this, SWIGTYPE_p_Ogre__SharedPtrT_Ogre__listT_Ogre__SharedPtrT_Ogre__AbstractNode_t_t__type_t.getCPtr(nodes), group, doImports, doObjects, doVariables);
  }

  public boolean _compile(SWIGTYPE_p_Ogre__SharedPtrT_Ogre__listT_Ogre__SharedPtrT_Ogre__AbstractNode_t_t__type_t nodes, String group, boolean doImports, boolean doObjects) {
    return OgreJNI.ScriptCompiler__compile__SWIG_1(swigCPtr, this, SWIGTYPE_p_Ogre__SharedPtrT_Ogre__listT_Ogre__SharedPtrT_Ogre__AbstractNode_t_t__type_t.getCPtr(nodes), group, doImports, doObjects);
  }

  public boolean _compile(SWIGTYPE_p_Ogre__SharedPtrT_Ogre__listT_Ogre__SharedPtrT_Ogre__AbstractNode_t_t__type_t nodes, String group, boolean doImports) {
    return OgreJNI.ScriptCompiler__compile__SWIG_2(swigCPtr, this, SWIGTYPE_p_Ogre__SharedPtrT_Ogre__listT_Ogre__SharedPtrT_Ogre__AbstractNode_t_t__type_t.getCPtr(nodes), group, doImports);
  }

  public boolean _compile(SWIGTYPE_p_Ogre__SharedPtrT_Ogre__listT_Ogre__SharedPtrT_Ogre__AbstractNode_t_t__type_t nodes, String group) {
    return OgreJNI.ScriptCompiler__compile__SWIG_3(swigCPtr, this, SWIGTYPE_p_Ogre__SharedPtrT_Ogre__listT_Ogre__SharedPtrT_Ogre__AbstractNode_t_t__type_t.getCPtr(nodes), group);
  }

  public void addError(long code, String file, int line, String msg) {
    OgreJNI.ScriptCompiler_addError__SWIG_0(swigCPtr, this, code, file, line, msg);
  }

  public void addError(long code, String file, int line) {
    OgreJNI.ScriptCompiler_addError__SWIG_1(swigCPtr, this, code, file, line);
  }

  public void setListener(ScriptCompilerListener listener) {
    OgreJNI.ScriptCompiler_setListener(swigCPtr, this, ScriptCompilerListener.getCPtr(listener), listener);
  }

  public ScriptCompilerListener getListener() {
    long cPtr = OgreJNI.ScriptCompiler_getListener(swigCPtr, this);
    return (cPtr == 0) ? null : new ScriptCompilerListener(cPtr, false);
  }

  public String getResourceGroup() {
    return OgreJNI.ScriptCompiler_getResourceGroup(swigCPtr, this);
  }

  public boolean _fireEvent(ScriptCompilerEvent evt, SWIGTYPE_p_void retval) {
    return OgreJNI.ScriptCompiler__fireEvent(swigCPtr, this, ScriptCompilerEvent.getCPtr(evt), evt, SWIGTYPE_p_void.getCPtr(retval));
  }

  public long registerCustomWordId(String word) {
    return OgreJNI.ScriptCompiler_registerCustomWordId(swigCPtr, this, word);
  }

  public final static int CE_STRINGEXPECTED = OgreJNI.ScriptCompiler_CE_STRINGEXPECTED_get();
  public final static int CE_NUMBEREXPECTED = OgreJNI.ScriptCompiler_CE_NUMBEREXPECTED_get();
  public final static int CE_FEWERPARAMETERSEXPECTED = OgreJNI.ScriptCompiler_CE_FEWERPARAMETERSEXPECTED_get();
  public final static int CE_VARIABLEEXPECTED = OgreJNI.ScriptCompiler_CE_VARIABLEEXPECTED_get();
  public final static int CE_UNDEFINEDVARIABLE = OgreJNI.ScriptCompiler_CE_UNDEFINEDVARIABLE_get();
  public final static int CE_OBJECTNAMEEXPECTED = OgreJNI.ScriptCompiler_CE_OBJECTNAMEEXPECTED_get();
  public final static int CE_OBJECTALLOCATIONERROR = OgreJNI.ScriptCompiler_CE_OBJECTALLOCATIONERROR_get();
  public final static int CE_INVALIDPARAMETERS = OgreJNI.ScriptCompiler_CE_INVALIDPARAMETERS_get();
  public final static int CE_DUPLICATEOVERRIDE = OgreJNI.ScriptCompiler_CE_DUPLICATEOVERRIDE_get();
  public final static int CE_UNEXPECTEDTOKEN = OgreJNI.ScriptCompiler_CE_UNEXPECTEDTOKEN_get();
  public final static int CE_OBJECTBASENOTFOUND = OgreJNI.ScriptCompiler_CE_OBJECTBASENOTFOUND_get();
  public final static int CE_UNSUPPORTEDBYRENDERSYSTEM = OgreJNI.ScriptCompiler_CE_UNSUPPORTEDBYRENDERSYSTEM_get();
  public final static int CE_REFERENCETOANONEXISTINGOBJECT = OgreJNI.ScriptCompiler_CE_REFERENCETOANONEXISTINGOBJECT_get();

  public final static int ID_ON = OgreJNI.ScriptCompiler_ID_ON_get();
  public final static int ID_OFF = OgreJNI.ScriptCompiler_ID_OFF_get();
  public final static int ID_TRUE = OgreJNI.ScriptCompiler_ID_TRUE_get();
  public final static int ID_FALSE = OgreJNI.ScriptCompiler_ID_FALSE_get();
  public final static int ID_YES = OgreJNI.ScriptCompiler_ID_YES_get();
  public final static int ID_NO = OgreJNI.ScriptCompiler_ID_NO_get();

}
