/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public class ShadowTextureManager {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ShadowTextureManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ShadowTextureManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_ShadowTextureManager(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ShadowTextureManager() {
    this(OgreJNI.new_ShadowTextureManager(), true);
  }

  public void getShadowTextures(SWIGTYPE_p_Ogre__vectorT_Ogre__ShadowTextureConfig_t__type config, SWIGTYPE_p_Ogre__vectorT_Ogre__SharedPtrT_Ogre__Texture_t_t__type listToPopulate) {
    OgreJNI.ShadowTextureManager_getShadowTextures(swigCPtr, this, SWIGTYPE_p_Ogre__vectorT_Ogre__ShadowTextureConfig_t__type.getCPtr(config), SWIGTYPE_p_Ogre__vectorT_Ogre__SharedPtrT_Ogre__Texture_t_t__type.getCPtr(listToPopulate));
  }

  public TexturePtr getNullShadowTexture(PixelFormat format) {
    return new TexturePtr(OgreJNI.ShadowTextureManager_getNullShadowTexture(swigCPtr, this, format.swigValue()), true);
  }

  public void clearUnused() {
    OgreJNI.ShadowTextureManager_clearUnused(swigCPtr, this);
  }

  public void clear() {
    OgreJNI.ShadowTextureManager_clear(swigCPtr, this);
  }

  public static ShadowTextureManager getSingleton() {
    return new ShadowTextureManager(OgreJNI.ShadowTextureManager_getSingleton(), false);
  }

}
