/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public class ShadowTextureConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ShadowTextureConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ShadowTextureConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_ShadowTextureConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setWidth(long value) {
    OgreJNI.ShadowTextureConfig_width_set(swigCPtr, this, value);
  }

  public long getWidth() {
    return OgreJNI.ShadowTextureConfig_width_get(swigCPtr, this);
  }

  public void setHeight(long value) {
    OgreJNI.ShadowTextureConfig_height_set(swigCPtr, this, value);
  }

  public long getHeight() {
    return OgreJNI.ShadowTextureConfig_height_get(swigCPtr, this);
  }

  public void setFormat(PixelFormat value) {
    OgreJNI.ShadowTextureConfig_format_set(swigCPtr, this, value.swigValue());
  }

  public PixelFormat getFormat() {
    return PixelFormat.swigToEnum(OgreJNI.ShadowTextureConfig_format_get(swigCPtr, this));
  }

  public void setFsaa(long value) {
    OgreJNI.ShadowTextureConfig_fsaa_set(swigCPtr, this, value);
  }

  public long getFsaa() {
    return OgreJNI.ShadowTextureConfig_fsaa_get(swigCPtr, this);
  }

  public void setDepthBufferPoolId(int value) {
    OgreJNI.ShadowTextureConfig_depthBufferPoolId_set(swigCPtr, this, value);
  }

  public int getDepthBufferPoolId() {
    return OgreJNI.ShadowTextureConfig_depthBufferPoolId_get(swigCPtr, this);
  }

  public ShadowTextureConfig() {
    this(OgreJNI.new_ShadowTextureConfig(), true);
  }

}
