/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public class StringVectorPtr {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StringVectorPtr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StringVectorPtr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_StringVectorPtr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StringVectorPtr() {
    this(OgreJNI.new_StringVectorPtr__SWIG_1(), true);
  }

  public StringVectorPtr(StringVectorPtr r) {
    this(OgreJNI.new_StringVectorPtr__SWIG_2(StringVectorPtr.getCPtr(r), r), true);
  }

  public StringVector __ref__() {
    return new StringVector(OgreJNI.StringVectorPtr___ref__(swigCPtr, this), false);
  }

  public StringVector __deref__() {
    long cPtr = OgreJNI.StringVectorPtr___deref__(swigCPtr, this);
    return (cPtr == 0) ? null : new StringVector(cPtr, false);
  }

  public StringVector get() {
    long cPtr = OgreJNI.StringVectorPtr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new StringVector(cPtr, false);
  }

  public boolean unique() {
    return OgreJNI.StringVectorPtr_unique(swigCPtr, this);
  }

  public int use_count() {
    return OgreJNI.StringVectorPtr_use_count(swigCPtr, this);
  }

  public void reset() {
    OgreJNI.StringVectorPtr_reset__SWIG_0(swigCPtr, this);
  }

  public void reset(StringVector rep) {
    OgreJNI.StringVectorPtr_reset__SWIG_1(swigCPtr, this, StringVector.getCPtr(rep), rep);
  }

  public long capacity() {
    return OgreJNI.StringVectorPtr_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    OgreJNI.StringVectorPtr_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return OgreJNI.StringVectorPtr_isEmpty(swigCPtr, this);
  }

  public void clear() {
    OgreJNI.StringVectorPtr_clear(swigCPtr, this);
  }

  private int doSize() {
    return OgreJNI.StringVectorPtr_doSize(swigCPtr, this);
  }

  private void doAdd(String value) {
    OgreJNI.StringVectorPtr_doAdd__SWIG_0(swigCPtr, this, value);
  }

  private void doAdd(int index, String value) {
    OgreJNI.StringVectorPtr_doAdd__SWIG_1(swigCPtr, this, index, value);
  }

  private String doRemove(int index) {
    return OgreJNI.StringVectorPtr_doRemove(swigCPtr, this, index);
  }

  private String doGet(int index) {
    return OgreJNI.StringVectorPtr_doGet(swigCPtr, this, index);
  }

  private String doSet(int index, String value) {
    return OgreJNI.StringVectorPtr_doSet(swigCPtr, this, index, value);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    OgreJNI.StringVectorPtr_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
