/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public class SubEntityList extends java.util.AbstractList<SubEntity> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SubEntityList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SubEntityList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_SubEntityList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SubEntityList(SubEntity[] initialElements) {
    this();
    for (SubEntity element : initialElements) {
      add(element);
    }
  }

  public SubEntityList(Iterable<SubEntity> initialElements) {
    this();
    for (SubEntity element : initialElements) {
      add(element);
    }
  }

  public SubEntity get(int index) {
    return doGet(index);
  }

  public SubEntity set(int index, SubEntity e) {
    return doSet(index, e);
  }

  public boolean add(SubEntity e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, SubEntity e) {
    modCount++;
    doAdd(index, e);
  }

  public SubEntity remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public SubEntityList() {
    this(OgreJNI.new_SubEntityList__SWIG_0(), true);
  }

  public SubEntityList(SubEntityList other) {
    this(OgreJNI.new_SubEntityList__SWIG_1(SubEntityList.getCPtr(other), other), true);
  }

  public long capacity() {
    return OgreJNI.SubEntityList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    OgreJNI.SubEntityList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return OgreJNI.SubEntityList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    OgreJNI.SubEntityList_clear(swigCPtr, this);
  }

  public SubEntityList(int count) {
    this(OgreJNI.new_SubEntityList__SWIG_2(count), true);
  }

  public SubEntityList(int count, SubEntity value) {
    this(OgreJNI.new_SubEntityList__SWIG_3(count, SubEntity.getCPtr(value), value), true);
  }

  private int doSize() {
    return OgreJNI.SubEntityList_doSize(swigCPtr, this);
  }

  private void doAdd(SubEntity value) {
    OgreJNI.SubEntityList_doAdd__SWIG_0(swigCPtr, this, SubEntity.getCPtr(value), value);
  }

  private void doAdd(int index, SubEntity value) {
    OgreJNI.SubEntityList_doAdd__SWIG_1(swigCPtr, this, index, SubEntity.getCPtr(value), value);
  }

  private SubEntity doRemove(int index) {
    long cPtr = OgreJNI.SubEntityList_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new SubEntity(cPtr, false);
  }

  private SubEntity doGet(int index) {
    long cPtr = OgreJNI.SubEntityList_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new SubEntity(cPtr, false);
  }

  private SubEntity doSet(int index, SubEntity value) {
    long cPtr = OgreJNI.SubEntityList_doSet(swigCPtr, this, index, SubEntity.getCPtr(value), value);
    return (cPtr == 0) ? null : new SubEntity(cPtr, false);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    OgreJNI.SubEntityList_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
