/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public class SubMeshList extends java.util.AbstractList<SubMesh> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SubMeshList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SubMeshList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreJNI.delete_SubMeshList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SubMeshList(SubMesh[] initialElements) {
    this();
    for (SubMesh element : initialElements) {
      add(element);
    }
  }

  public SubMeshList(Iterable<SubMesh> initialElements) {
    this();
    for (SubMesh element : initialElements) {
      add(element);
    }
  }

  public SubMesh get(int index) {
    return doGet(index);
  }

  public SubMesh set(int index, SubMesh e) {
    return doSet(index, e);
  }

  public boolean add(SubMesh e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, SubMesh e) {
    modCount++;
    doAdd(index, e);
  }

  public SubMesh remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public SubMeshList() {
    this(OgreJNI.new_SubMeshList__SWIG_0(), true);
  }

  public SubMeshList(SubMeshList other) {
    this(OgreJNI.new_SubMeshList__SWIG_1(SubMeshList.getCPtr(other), other), true);
  }

  public long capacity() {
    return OgreJNI.SubMeshList_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    OgreJNI.SubMeshList_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return OgreJNI.SubMeshList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    OgreJNI.SubMeshList_clear(swigCPtr, this);
  }

  public SubMeshList(int count) {
    this(OgreJNI.new_SubMeshList__SWIG_2(count), true);
  }

  public SubMeshList(int count, SubMesh value) {
    this(OgreJNI.new_SubMeshList__SWIG_3(count, SubMesh.getCPtr(value), value), true);
  }

  private int doSize() {
    return OgreJNI.SubMeshList_doSize(swigCPtr, this);
  }

  private void doAdd(SubMesh value) {
    OgreJNI.SubMeshList_doAdd__SWIG_0(swigCPtr, this, SubMesh.getCPtr(value), value);
  }

  private void doAdd(int index, SubMesh value) {
    OgreJNI.SubMeshList_doAdd__SWIG_1(swigCPtr, this, index, SubMesh.getCPtr(value), value);
  }

  private SubMesh doRemove(int index) {
    long cPtr = OgreJNI.SubMeshList_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new SubMesh(cPtr, false);
  }

  private SubMesh doGet(int index) {
    long cPtr = OgreJNI.SubMeshList_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new SubMesh(cPtr, false);
  }

  private SubMesh doSet(int index, SubMesh value) {
    long cPtr = OgreJNI.SubMeshList_doSet(swigCPtr, this, index, SubMesh.getCPtr(value), value);
    return (cPtr == 0) ? null : new SubMesh(cPtr, false);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    OgreJNI.SubMeshList_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
