/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public class TextAreaOverlayElement extends OverlayElement {
  private transient long swigCPtr;

  protected TextAreaOverlayElement(long cPtr, boolean cMemoryOwn) {
    super(OgreOverlayJNI.TextAreaOverlayElement_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TextAreaOverlayElement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreOverlayJNI.delete_TextAreaOverlayElement(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public TextAreaOverlayElement(String name) {
    this(OgreOverlayJNI.new_TextAreaOverlayElement(name), true);
  }

  public void initialise() {
    OgreOverlayJNI.TextAreaOverlayElement_initialise(swigCPtr, this);
  }

  public void _releaseManualHardwareResources() {
    OgreOverlayJNI.TextAreaOverlayElement__releaseManualHardwareResources(swigCPtr, this);
  }

  public void _restoreManualHardwareResources() {
    OgreOverlayJNI.TextAreaOverlayElement__restoreManualHardwareResources(swigCPtr, this);
  }

  public void setCaption(SWIGTYPE_p_UTFString text) {
    OgreOverlayJNI.TextAreaOverlayElement_setCaption(swigCPtr, this, SWIGTYPE_p_UTFString.getCPtr(text));
  }

  public void setCharHeight(float height) {
    OgreOverlayJNI.TextAreaOverlayElement_setCharHeight(swigCPtr, this, height);
  }

  public float getCharHeight() {
    return OgreOverlayJNI.TextAreaOverlayElement_getCharHeight(swigCPtr, this);
  }

  public void setSpaceWidth(float width) {
    OgreOverlayJNI.TextAreaOverlayElement_setSpaceWidth(swigCPtr, this, width);
  }

  public float getSpaceWidth() {
    return OgreOverlayJNI.TextAreaOverlayElement_getSpaceWidth(swigCPtr, this);
  }

  public void setFontName(String font) {
    OgreOverlayJNI.TextAreaOverlayElement_setFontName(swigCPtr, this, font);
  }

  public SWIGTYPE_p_Ogre__SharedPtrT_Ogre__Font_t getFont() {
    return new SWIGTYPE_p_Ogre__SharedPtrT_Ogre__Font_t(OgreOverlayJNI.TextAreaOverlayElement_getFont(swigCPtr, this), false);
  }

  public String getTypeName() {
    return OgreOverlayJNI.TextAreaOverlayElement_getTypeName(swigCPtr, this);
  }

  public MaterialPtr getMaterial() {
    return new MaterialPtr(OgreOverlayJNI.TextAreaOverlayElement_getMaterial(swigCPtr, this), false);
  }

  public void getRenderOperation(RenderOperation op) {
    OgreOverlayJNI.TextAreaOverlayElement_getRenderOperation(swigCPtr, this, RenderOperation.getCPtr(op), op);
  }

  public void setColour(ColourValue col) {
    OgreOverlayJNI.TextAreaOverlayElement_setColour(swigCPtr, this, ColourValue.getCPtr(col), col);
  }

  public ColourValue getColour() {
    return new ColourValue(OgreOverlayJNI.TextAreaOverlayElement_getColour(swigCPtr, this), false);
  }

  public void setColourBottom(ColourValue col) {
    OgreOverlayJNI.TextAreaOverlayElement_setColourBottom(swigCPtr, this, ColourValue.getCPtr(col), col);
  }

  public ColourValue getColourBottom() {
    return new ColourValue(OgreOverlayJNI.TextAreaOverlayElement_getColourBottom(swigCPtr, this), false);
  }

  public void setColourTop(ColourValue col) {
    OgreOverlayJNI.TextAreaOverlayElement_setColourTop(swigCPtr, this, ColourValue.getCPtr(col), col);
  }

  public ColourValue getColourTop() {
    return new ColourValue(OgreOverlayJNI.TextAreaOverlayElement_getColourTop(swigCPtr, this), false);
  }

  public void setAlignment(TextAreaOverlayElement.Alignment a) {
    OgreOverlayJNI.TextAreaOverlayElement_setAlignment(swigCPtr, this, a.swigValue());
  }

  public TextAreaOverlayElement.Alignment getAlignment() {
    return TextAreaOverlayElement.Alignment.swigToEnum(OgreOverlayJNI.TextAreaOverlayElement_getAlignment(swigCPtr, this));
  }

  public void setMetricsMode(GuiMetricsMode gmm) {
    OgreOverlayJNI.TextAreaOverlayElement_setMetricsMode(swigCPtr, this, gmm.swigValue());
  }

  public void _update() {
    OgreOverlayJNI.TextAreaOverlayElement__update(swigCPtr, this);
  }

  public final static class Alignment {
    public final static TextAreaOverlayElement.Alignment Left = new TextAreaOverlayElement.Alignment("Left");
    public final static TextAreaOverlayElement.Alignment Right = new TextAreaOverlayElement.Alignment("Right");
    public final static TextAreaOverlayElement.Alignment Center = new TextAreaOverlayElement.Alignment("Center");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static Alignment swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + Alignment.class + " with value " + swigValue);
    }

    private Alignment(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private Alignment(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private Alignment(String swigName, Alignment swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static Alignment[] swigValues = { Left, Right, Center };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
