/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public class TrayListener {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TrayListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TrayListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgreBitesJNI.delete_TrayListener(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void buttonHit(Button button) {
    OgreBitesJNI.TrayListener_buttonHit(swigCPtr, this, Button.getCPtr(button), button);
  }

  public void itemSelected(SelectMenu menu) {
    OgreBitesJNI.TrayListener_itemSelected(swigCPtr, this, SelectMenu.getCPtr(menu), menu);
  }

  public void labelHit(Label label) {
    OgreBitesJNI.TrayListener_labelHit(swigCPtr, this, Label.getCPtr(label), label);
  }

  public void sliderMoved(Slider slider) {
    OgreBitesJNI.TrayListener_sliderMoved(swigCPtr, this, Slider.getCPtr(slider), slider);
  }

  public void checkBoxToggled(CheckBox box) {
    OgreBitesJNI.TrayListener_checkBoxToggled(swigCPtr, this, CheckBox.getCPtr(box), box);
  }

  public void okDialogClosed(SWIGTYPE_p_Ogre__DisplayString message) {
    OgreBitesJNI.TrayListener_okDialogClosed(swigCPtr, this, SWIGTYPE_p_Ogre__DisplayString.getCPtr(message));
  }

  public void yesNoDialogClosed(SWIGTYPE_p_Ogre__DisplayString question, boolean yesHit) {
    OgreBitesJNI.TrayListener_yesNoDialogClosed(swigCPtr, this, SWIGTYPE_p_Ogre__DisplayString.getCPtr(question), yesHit);
  }

  public TrayListener() {
    this(OgreBitesJNI.new_TrayListener(), true);
  }

}
