/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.Ogre;

public final class VSOutputCompactPolicy {
  public final static VSOutputCompactPolicy VSOCP_LOW = new VSOutputCompactPolicy("VSOCP_LOW", OgreRTShaderJNI.VSOCP_LOW_get());
  public final static VSOutputCompactPolicy VSOCP_MEDIUM = new VSOutputCompactPolicy("VSOCP_MEDIUM", OgreRTShaderJNI.VSOCP_MEDIUM_get());
  public final static VSOutputCompactPolicy VSOCP_HIGH = new VSOutputCompactPolicy("VSOCP_HIGH", OgreRTShaderJNI.VSOCP_HIGH_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static VSOutputCompactPolicy swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + VSOutputCompactPolicy.class + " with value " + swigValue);
  }

  private VSOutputCompactPolicy(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private VSOutputCompactPolicy(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private VSOutputCompactPolicy(String swigName, VSOutputCompactPolicy swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static VSOutputCompactPolicy[] swigValues = { VSOCP_LOW, VSOCP_MEDIUM, VSOCP_HIGH };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

